// =============================================
// MoneyShop - Unified i18n System
// =============================================

export type Language = "tr" | "en" | "ar" | "ku" | "fr" | "ru";
export type Dir = "ltr" | "rtl";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "tr", label: "Türkçe", flag: "🇹🇷" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
  { code: "ku", label: "Kurdî", flag: "🏴" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
];

export const VALID_LANGUAGES = LANGUAGES.map((l) => l.code);
export const STORAGE_KEY = "moneyshop-lang";

export function getLangDir(lang: Language): Dir {
  return lang === "ar" ? "rtl" : "ltr";
}

export function getInitialLang(): Language {
  if (typeof window === "undefined") return "tr";
  const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
  if (saved && VALID_LANGUAGES.includes(saved)) return saved;
  return "tr";
}

export function getDashboardLang(): Language {
  return getInitialLang();
}

type NestedMessages = { [key: string]: string | string[] | NestedMessages };

export function t(lang: Language, path: string): string {
  const keys = path.split(".");
  let result: NestedMessages = messages[lang];
  for (const key of keys) {
    const val = result[key];
    if (typeof val === "string") return val;
    if (val == null || Array.isArray(val)) return path;
    result = val;
  }
  return typeof result === "string" ? result : path;
}

export function tArray(lang: Language, path: string): string[] {
  const keys = path.split(".");
  let result: NestedMessages = messages[lang];
  for (const key of keys) {
    const val = result[key];
    if (Array.isArray(val)) return val;
    if (val == null || typeof val === "string") return [];
    result = val;
  }
  return [];
}

type FlatDict = Record<string, Record<Language, string>>;

export function tFlat(key: string, fallback?: string): string {
  const lang = getDashboardLang();
  const entry = flatDict[key];
  if (!entry) return fallback ?? key;
  return entry[lang] ?? entry["tr"] ?? key;
}

export function tFlatWithVars(key: string, vars: Record<string, string | number>): string {
  let result = tFlat(key);
  for (const [k, v] of Object.entries(vars)) {
    result = result.replace(`{{${k}}}`, String(v));
  }
  return result;
}

// ─── Landing Messages ─────────────────────────────────────
// Her dil kendi tam mesaj setini içerir.
const TR: NestedMessages = {
  nav: { services:"Hizmetler", howItWorks:"Nasıl Çalışır", card:"MoneyShop Card", features:"Özellikler", compliance:"Uyumluluk", roadmap:"Yol Haritası", impact:"Etki", pricing:"Ücretlendirme", login:"Giriş Yap", register:"Kayıt Ol", getStarted:"Hemen Başla", logout:"Çıkış Yap", bireysel:"Bireysel", kurumsal:"Kurumsal", individual:"Bireysel", corporate:"Kurumsal", moneyTransfer:"Para Transferi", investment:"Yatırım", paymentOperations:"Ödeme İşlemleri", physicalPayment:"Fiziki Ödeme Al", onlinePayment:"Online Ödeme Al", paymentDistribution:"Ödeme Dağıt", cardSolutions:"Kart Çözümleri", faq:"SSS" },
  hero: { titleStart:"Irak'ın", titleHighlight:"Dijital Ödeme", titleEnd:"Devrimine Güç Veriyoruz", badge:"CBI Lisanslı Ödeme Hizmet Sağlayıcı", description:"MoneyShop, Irak ve Kürdistan Bölgesi'ndeki işletmelere fiziksel POS'tan çevrimiçi ödeme geçitlerine kadar güvenli, uyumlu ve sorunsuz ödeme altyapısı sunar.", cta:"Hemen Başvur", secondary:"Daha Fazla Bilgi", merchants:"İşletme", uptime:"Çalışma Süresi", support:"Destek" },
  features: { title:"Neden", highlight:"MoneyShop?", subtitle:"Irak için inşa edildi, dijital ödemelerin geleceği için tasarlandı.", phoneScan:"QR Tara", phoneTransfer:"Transfer", phoneReports:"Raporlar", phoneRecent:"Son İşlemler", dashboardTitle:"Gerçek Zamanlı Panel", dashboardDesc:"Sezgisel tüccar panelimiz aracılığıyla tüm işlemlerinizi, gelirlerinizi ve mutabakatlarınızı gerçek zamanlı izleyin.", securityTitle:"Banka Düzeyinde Güvenlik", securityDesc:"Her işlemi koruyan uçtan uca şifreleme, dolandırıcılık tespiti ve PCI-DSS uyumlu altyapı.", iqdTitle:"IQD Yerel İşleme", iqdDesc:"Tüm işlemler Irak Dinarı cinsinden işlenir ve yerel banka hesabınıza otomatik yerleşim sağlanır.", apiTitle:"Geliştirici Dostu API", apiDesc:"Mevcut sistemlerinize ve uygulamalarınıza kolay entegrasyon için SDK'lar ile kapsamlı REST API." },
  services: { title:"Komple Ödeme", highlight:"Altyapısı", subtitle:"Irak pazarına özel olarak tasarlanmış, fiziksel POS'tan dijital ödeme geçitlerine kadar uçtan uca ödeme çözümleri.", posTitle:"Fiziksel POS Terminalleri", posDesc:"Tüm yerel banka kartlarını destekleyen, mağaza içi ödeme kabulü için son teknoloji POS cihazları.", gatewayTitle:"Çevrimiçi Ödeme Geçidi", gatewayDesc:"Çevrimiçi işletmeniz için kolay API entegrasyonu ile güvenli e-ticaret ödeme işleme.", merchantTitle:"Tüccar Yönetimi", merchantDesc:"Komple tüccar kaydı, risk profili oluşturma, komisyon yönetimi ve analitik paneli.", settlementTitle:"Günlük Mutabakat", settlementDesc:"Tüccarlara zamanında ödeme sağlayan otomatik günlük mutabakat ve fon yerleşimi.", bankTitle:"Banka Entegrasyonu", bankDesc:"IQD işlemleri için lisanslı Irak bankalarıyla sorunsuz teknik ve operasyonel entegrasyon.", linksTitle:"Ödeme Bağlantıları", linksDesc:"Uzaktan tahsilat ve dijital fatura çözümleri için güvenli ödeme bağlantıları oluşturun.",     transfersTitle:"Hızlı ve Kolay Para Transferleri", fastTitle:"FAST Para Transferi", fastDesc:"7/24 anında para transferi. Saniyeler içinde gönderin, hemen ulaşsın. Tüm bankalar arası kesintisiz ve ücretsiz transfer.", eftTitle:"Havale & EFT", eftDesc:"Geleneksel bankacılık işlemleriniz tek platformdan yönetin. Dakikalar içinde güvenli havale ve EFT gönderimi.", internationalTitle:"Yurt Dışından Para Al", internationalDesc:"Dünyanın her yerinden para almanın en kolay yolu. Uluslararası transferleri anında takip edin ve yönetin.", ibanTitle:"MoneyShop IBAN & Kolay Adres", ibanDesc:"Size özel IBAN ve kolay adresinizle para transferlerinizi zahmetsiz hale getirin. QR kod ile anında gönderim.", requestTitle:"Ödeme İste", requestDesc:"Müşterilerinizden veya iş ortaklarınızdan tek tıkla ödeme isteyin. Link gönderin, takibini yapın, tahsilatı otomatikleştirin.", secureTitle:"Güvenli Ödeme", secureDesc:"3D Secure ve tokenizasyon altyapısı ile korunan ödeme işlemleri. Dolandırıcılığa karşı gerçek zamanlı izleme ve bildirim." },
  how: { title:"Başlamak için", highlight:"4 Basit Adım", subtitle:"Kayıttan ilk ödemenize kadar — onboarding sürecini sorunsuz ve hızlı hale getiriyoruz.", step1Title:"Kayıt ve KYC", step1Desc:"İşletme belgelerinizi gönderin ve güvenli portalımız üzerinden kimlik doğrulamayı tamamlayın.", step2Title:"Sözleşme İmzala", step2Desc:"Şeffaf komisyon oranları ve şartlarla tüccar sözleşmesini inceleyin ve imzalayın.", step3Title:"Kurulum ve Entegrasyon", step3Desc:"POS terminalinizi alın veya ödeme geçidi API'mizi web sitenize entegre edin.", step4Title:"Kabul Etmeye Başla", step4Desc:"Gerçek zamanlı panel takibi ile anında ödeme almaya başlayın." },
  impact: { title:"Ekonomik ve", highlight:"Sosyal Etki", subtitle:"Irak'ın finansal ekosisteminde olumlu değişim yaratmak.", digitalTitle:"Dijital Benimseme", digitalDesc:"Iraklı işletmeler ve tüketiciler arasında dijital ödeme benimsemesini hızlandırmak.", formalTitle:"Formal Ekonomi", formalDesc:"Şeffaf, izlenebilir dijital işlemler yoluyla kayıt dışı ekonomiyi azaltmak.", fastTitle:"Hızlı Tahsilat", fastDesc:"İşletmelerin anında ve güvenli bir şekilde ödeme tahsil etmesini sağlamak.", regionalTitle:"Bölgesel Büyüme", regionalDesc:"Fintech inovasyonu yoluyla KRG ve Irak'ın ekonomik kalkınmasına katkıda bulunmak." },
  compliance: { title:"Tamamen", highlight:"Düzenlenmiş ve Güvenli", subtitle:"Tam AML/KYC uyumluluğu ve kurumsal düzeyde güvenlik ile CBI düzenlemeleri altında faaliyet gösteriyoruz.", kycTitle:"KYC / AML Uyumluluğu", kycDesc:"CBI gereklilikleri ve uluslararası standartlarla tam uyumlu Kapsamlı Müşteri Tanıma ve Kara Para Aklamayı Önleme prosedürleri.", dataTitle:"Veri Şifreleme", dataDesc:"Hassas finansal bilgilerin tam korunmasını sağlayan askeri düzeyde SSL/TLS şifreleme, tokenizasyon ve güvenli veri depolama.", monitoringTitle:"İşlem İzleme", monitoringDesc:"Yapay zeka destekli şüpheli aktivite tespiti, gerçek zamanlı dolandırıcılık izleme ve mevzuat uyumluluğu için kapsamlı denetim izleri." },
  roadmap: { title:"Büyüme", highlight:"Yolculuğumuz", subtitle:"Irak'ın en güvenilir ödeme altyapısını oluşturmak için aşamalı bir yaklaşım.", phase1:"1. AŞAMA — TEMEL", phase1Title:"Şirket Kuruluşu ve Lisanslama", phase1Items:["Irak'ta şirket tescili","CBI lisans başvurusu ve onayı","Banka ortaklıkları kuruldu","Fiziksel POS altyapısı dağıtıldı"], phase2:"2. AŞAMA — DİJİTAL GENİŞLEME", phase2Title:"Çevrimiçi Platform Lansmanı", phase2Items:["Çevrimiçi ödeme geçidi aktivasyonu","Tüccar yönetim platformu","Raporlama ve analitik paneli","Tüccarlar için mobil uygulama"], phase3:"3. AŞAMA — ÖLÇEKLENME VE GENİŞLEME", phase3Title:"Bölgesel Büyüme", phase3Items:["Ülke çapında hizmet genişletme","Uluslararası ortaklıklar","Gelişmiş fintech entegrasyonları","Sınır ötesi ödeme yetenekleri"] },
  tech: { title:"Teknoloji", highlight:"Altyapımız", subtitle:"En son teknolojilerle güçlendirilmiş." },
  trusted: { title:"Güvenilir Platform", centralBank:"Merkez Bankası Uyumlu", krg:"KRG Onaylı", iqBanks:"Irak Bankaları", merchants:"İşletmeler" },
  cta: { title:"Ödeme Deneyiminizi<br/>Dönüştürmeye <span class='highlight'>Hazır mısınız?</span>", description:"Dijital ödemeleri güvenli ve verimli bir şekilde kabul etmek için MoneyShop'u kullanan yüzlerce Iraklı işletmeye katılın.", primary:"Tüccar Hesabına Başvur", secondary:"Satış Ekibiyle İletişime Geç" },
  card: { title:"MoneyShop", highlight:"Card", subtitle:"İşletmenizin finansal yönetimini tek kartta toplayın. POS, online ödemeler ve daha fazlası için özel olarak tasarlanmış akıllı kart çözümlerimizle tanışın.", popular:"EN POPÜLER", standart:{name:"Standart", price:"Ücretsiz", period:"", features:["Ücretsiz başvuru ve yıllık aidat","Günlük 5.000 IQD işlem limiti","POS ve ATM'de kullanım","Online ödeme desteği","SMS işlem bildirimleri","Temel müşteri desteği"], cta:"Hemen Başvur"}, silver:{name:"Silver", price:"19.900 IQD", period:"/ay", features:["Günlük 50.000 IQD işlem limiti","Öncelikli müşteri desteği","%0,7 işlem komisyonu","Mobil uygulama bildirimleri","Detaylı harcama raporları","Tüm Standart özellikler"], cta:"Hemen Başvur"}, gold:{name:"Gold", price:"49.900 IQD", period:"/ay", features:["Günlük 250.000 IQD işlem limiti","7/24 VIP müşteri desteği","%0,3 işlem komisyonu","Özel iş ortağı indirimleri","Ücretsiz uluslararası işlemler","Özel kart tasarımı","Tüm Silver özellikler"], cta:"Hemen Başvur"} },
  footer: { description:"Irak'ın lider Ödeme Hizmet Sağlayıcısı, Kürdistan Bölgesi ve ötesindeki işletmelere güvenli ve uyumlu dijital ödeme çözümleri sunar.", services:"Hizmetler", servicesList:["POS Terminalleri","Çevrimiçi Ödemeler","Ödeme Bağlantıları","Tüccar Portalı"], company:"Şirket", companyList:["Hakkımızda","Kariyer","Basın","Blog","İletişim"], legal:"Yasal", legalList:["Gizlilik Politikası","Kullanım Şartları","AML Politikası","KYC Politikası","Çerez Politikası"], contact:"İletişim", address:"Erbil, Kürdistan Bölgesi, Irak", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"Paz-Per: 09:00 - 18:00", copyright:"© 2026 MoneyShop. Tüm hakları saklıdır.", privacy:"Gizlilik", terms:"Koşullar", sitemap:"Site Haritası" },
};

const EN: NestedMessages = {
  nav: { services:"Services", howItWorks:"How It Works", card:"MoneyShop Card", features:"Features", compliance:"Compliance", roadmap:"Roadmap", impact:"Impact", pricing:"Pricing", login:"Login", register:"Register", getStarted:"Get Started", logout:"Log Out", bireysel:"Individual", kurumsal:"Corporate", individual:"Individual", corporate:"Corporate", moneyTransfer:"Money Transfer", investment:"Investment", paymentOperations:"Payment Operations", physicalPayment:"Accept Physical Payments", onlinePayment:"Accept Online Payments", paymentDistribution:"Distribute Payments", cardSolutions:"Card Solutions", faq:"FAQ" },
  hero: { titleStart:"Powering Iraq's", titleHighlight:"Digital Payment", titleEnd:"Revolution", badge:"CBI Licensed Payment Service Provider", description:"MoneyShop provides secure, compliant, and seamless payment infrastructure for businesses in Iraq and Kurdistan Region, from physical POS to online payment gateways.", cta:"Apply Now", secondary:"Learn More", merchants:"Businesses", uptime:"Uptime", support:"Support" },
  features: { title:"Why", highlight:"MoneyShop?", subtitle:"Built for Iraq, designed for the future of digital payments.", phoneScan:"Scan QR", phoneTransfer:"Transfer", phoneReports:"Reports", phoneRecent:"Recent Transactions", dashboardTitle:"Real-Time Dashboard", dashboardDesc:"Track all your transactions, revenue and settlements in real-time through our intuitive merchant dashboard.", securityTitle:"Bank-Grade Security", securityDesc:"End-to-end encryption protecting every transaction, fraud detection and PCI-DSS compliant infrastructure.", iqdTitle:"IQD Local Processing", iqdDesc:"All transactions are processed in Iraqi Dinar with automatic settlement to your local bank account.", apiTitle:"Developer-Friendly API", apiDesc:"Comprehensive REST API with SDKs for easy integration with your existing systems and applications." },
  services: { title:"Our Services", highlight:"Comprehensive Solutions", subtitle:"All the financial tools your business needs.", transfersTitle:"Transfer Services", fastTitle:"Fast Transfer", fastDesc:"Send money instantly to MoneyShop users.", eftTitle:"EFT", eftDesc:"Send money to bank accounts via EFT.", internationalTitle:"International Transfer", internationalDesc:"Send money anywhere in the world.", ibanTitle:"IBAN Transfer", ibanDesc:"Send money using IBAN number.", requestTitle:"Request Money", requestDesc:"Request money from others.", secureTitle:"Secure Transfer", secureDesc:"Transfer with advanced security." },
  how: { title:"How It Works", highlight:"4 Easy Steps", subtitle:"From registration to your first payment — we make the onboarding process seamless and fast.", step1Title:"Register & KYC", step1Desc:"Submit your business documents and complete identity verification through our secure portal.", step2Title:"Sign Agreement", step2Desc:"Review and sign the merchant agreement with transparent commission rates and terms.", step3Title:"Setup & Integration", step3Desc:"Get your POS terminal or integrate our payment gateway API into your website.", step4Title:"Start Accepting", step4Desc:"Start receiving payments instantly with real-time dashboard tracking." },
  impact: { title:"Economic &", highlight:"Social Impact", subtitle:"Creating positive change in Iraq's financial ecosystem.", digitalTitle:"Digital Adoption", digitalDesc:"Accelerating digital payment adoption between Iraqi businesses and consumers.", formalTitle:"Formal Economy", formalDesc:"Reducing the informal economy through transparent, traceable digital transactions.", fastTitle:"Fast Settlement", fastDesc:"Enabling businesses to collect payments instantly and securely.", regionalTitle:"Regional Growth", regionalDesc:"Contributing to KRG and Iraq's economic development through fintech innovation." },
  compliance: { title:"Fully", highlight:"Regulated & Secure", subtitle:"We operate under CBI regulations with full AML/KYC compliance and enterprise-grade security.", kycTitle:"KYC / AML Compliance", kycDesc:"Comprehensive Customer Identification and Anti-Money Laundering procedures fully compliant with CBI requirements and international standards.", dataTitle:"Data Encryption", dataDesc:"Military-grade SSL/TLS encryption, tokenization and secure data storage ensuring complete protection of sensitive financial information.", monitoringTitle:"Transaction Monitoring", monitoringDesc:"AI-powered suspicious activity detection, real-time fraud monitoring and comprehensive audit trails for regulatory compliance." },
  roadmap: { title:"Growth", highlight:"Our Journey", subtitle:"A phased approach to building Iraq's most trusted payment infrastructure.", phase1:"PHASE 1 — FOUNDATION", phase1Title:"Company Formation & Licensing", phase1Items:["Company registration in Iraq","CBI license application and approval","Bank partnerships established","Physical POS infrastructure deployed"], phase2:"PHASE 2 — DIGITAL EXPANSION", phase2Title:"Online Platform Launch", phase2Items:["Online payment gateway activation","Merchant management platform","Reporting and analytics dashboard","Mobile app for merchants"], phase3:"PHASE 3 — SCALE & EXPAND", phase3Title:"Regional Growth", phase3Items:["Nationwide service expansion","International partnerships","Advanced fintech integrations","Cross-border payment capabilities"] },
  tech: { title:"Technology", highlight:"Our Infrastructure", subtitle:"Powered by the latest technologies." },
  trusted: { title:"Trusted Platform", centralBank:"Central Bank Compliant", krg:"KRG Approved", iqBanks:"Iraq Banks", merchants:"Businesses" },
  cta: { title:"Ready to Transform<br/>Your Payment <span class='highlight'>Experience?</span>", description:"Join hundreds of Iraqi businesses using MoneyShop to accept digital payments securely and efficiently.", primary:"Apply for Merchant Account", secondary:"Contact Sales Team" },
  card: { title:"MoneyShop", highlight:"Card", subtitle:"Consolidate your business financial management into one card. Meet our smart card solutions designed specifically for POS, online payments and more.", popular:"MOST POPULAR", standart:{name:"Standard", price:"Free", period:"", features:["Free application and annual fee","5,000 IQD daily transaction limit","POS and ATM usage","Online payment support","SMS transaction notifications","Basic customer support"], cta:"Apply Now"}, silver:{name:"Silver", price:"19,900 IQD", period:"/mo", features:["50,000 IQD daily transaction limit","Priority customer support","0.7% transaction fee","Mobile app notifications","Detailed spending reports","All Standard features"], cta:"Apply Now"}, gold:{name:"Gold", price:"49,900 IQD", period:"/mo", features:["250,000 IQD daily transaction limit","24/7 VIP customer support","0.3% transaction fee","Exclusive partner discounts","Free international transactions","Custom card design","All Silver features"], cta:"Apply Now"} },
  footer: { description:"Iraq's leading Payment Service Provider, offering secure and compliant digital payment solutions for businesses in Kurdistan Region and beyond.", services:"Services", servicesList:["POS Terminals","Online Payments","Payment Links","Merchant Portal"], company:"Company", companyList:["About Us","Careers","Press","Blog","Contact"], legal:"Legal", legalList:["Privacy Policy","Terms of Service","AML Policy","KYC Policy","Cookie Policy"], contact:"Contact", address:"Erbil, Kurdistan Region, Iraq", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"Sun-Thu: 09:00 - 18:00", copyright:"© 2026 MoneyShop. All rights reserved.", privacy:"Privacy", terms:"Terms", sitemap:"Sitemap" },
};

const AR: NestedMessages = {
  nav: { services:"الخدمات", howItWorks:"كيف يعمل", card:"بطاقة MoneyShop", features:"الميزات", compliance:"الامتثال", roadmap:"خارطة الطريق", impact:"التأثير", pricing:"التسعير", login:"تسجيل الدخول", register:"التسجيل", getStarted:"ابدأ الآن", logout:"تسجيل الخروج", bireysel:"فرد", kurumsal:"مؤسسي", individual:"فرد", corporate:"مؤسسي", moneyTransfer:"تحويل الأموال", investment:"الاستثمار", paymentOperations:"عمليات الدفع", physicalPayment:"قبول المدفوعات الفعلية", onlinePayment:"قبول المدفوعات عبر الإنترنت", paymentDistribution:"توزيع المدفوعات", cardSolutions:"حلول البطاقات", faq:"الأسئلة الشائعة" },
  hero: { titleStart:"نُشيد", titleHighlight:"ثورة الدفع", titleEnd:"الرقمي في العراق", badge:"مزود خدمات الدفع المرخص من البنك المركزي", description:"توفر MoneyShop البنية التحتية للدفع الآمنة والمتوافقة والسلسة للشركات في العراق وإقليم كردستان، من أجهزة POS المادية إلى بوابات الدفع عبر الإنترنت.", cta:"تقديم الآن", secondary:"اعرف المزيد", merchants:"شركة", uptime:"وقت التشغيل", support:"دعم" },
  features: { title:"لماذا", highlight:"MoneyShop?", subtitle:"مصمم للعراق، مصمم لمستقبل المدفوعات الرقمية.", phoneScan:"مسح QR", phoneTransfer:"تحويل", phoneReports:"تقارير", phoneRecent:"آخر المعاملات", dashboardTitle:"لوحة تحكم في الوقت الفعلي", dashboardDesc:"تتبع جميع معاملاتك وإيراداتك وتسوياتك في الوقت الفعلي من خلال لوحة تحكم التاجر البديهية لدينا.", securityTitle:"أمان على مستوى البنك", securityDesc:"تشفير شامل من طرف إلى طرف يحمي كل معاملة، واكتشاف الاحتيال والبنية التحتية المتوافقة مع PCI-DSS.", iqdTitle:"معالجة محلية بالدينار العراقي", iqdDesc:"تتم معالجة جميع المعاملات بالدينار العراقي مع تسوية تلقائية إلى حسابك البنكي المحلي.", apiTitle:"واجهة برمجة تطبيقات صديقة للمطورين", apiDesc:"واجهة برمجة REST شاملة مع SDK لسهولة التكامل مع أنظمتك وتطبيقاتك الحالية." },
  services: { title:"خدماتنا", highlight:"حلول شاملة", subtitle:"جميع الأدوات المالية التي يحتاجها عملك.", transfersTitle:"خدمات التحويل", fastTitle:"تحويل سريع", fastDesc:"أرسل الأموال فوراً لمستخدمي MoneyShop.", eftTitle:"EFT", eftDesc:"أرسل الأموال لحسابات بنكية عبر EFT.", internationalTitle:"تحويل دولي", internationalDesc:"أرسل الأموال إلى أي مكان في العالم.", ibanTitle:"تحويل عبر IBAN", ibanDesc:"أرسل الأموال باستخدام رقم IBAN.", requestTitle:"طلب أموال", requestDesc:"اطلب أموالاً من الآخرين.", secureTitle:"تحويل آمن", secureDesc:"قم بالتحويل بأمان متقدم." },
  how: { title:"كيف يعمل", highlight:"4 خطوات سهلة", subtitle:"من التسجيل إلى أول دفعة لك — نجعل عملية التأهيل سلسة وسريعة.", step1Title:"التسجيل والتحقق", step1Desc:"أرسل مستندات عملك وأكمل التحقق من الهوية من خلال بوابتنا الآمنة.", step2Title:"توقيع الاتفاقية", step2Desc:"راجع ووقع اتفاقية التاجر مع نسب عمولة وشروط شفافة.", step3Title:"الإعداد والتكامل", step3Desc:"احصل على جهاز POS أو ادمج بوابة الدفع API في موقعك الإلكتروني.", step4Title:"ابدأ في القبول", step4Desc:"ابدأ في استلام المدفوعات فوراً مع لوحة تحكم تتبع في الوقت الفعلي." },
  impact: { title:"التأثير", highlight:"الاقتصادي والاجتماعي", subtitle:"خلق تغيير إيجابي في النظام المالي العراقي.", digitalTitle:"التبني الرقمي", digitalDesc:"تسريع تبني المدفوعات الرقمية بين الشركات والمستهلكين العراقيين.", formalTitle:"الاقتصاد الرسمي", formalDesc:"تقليل الاقتصاد غير الرسمي من خلال المعاملات الرقمية الشفافة وقابلة التتبع.", fastTitle:"التحصيل السريع", fastDesc:"تمكين الشركات من تحصيل المدفوعات فوراً وبشكل آمن.", regionalTitle:"النمو الإقليمي", regionalDesc:"المساهمة في التنمية الاقتصادية لإقليم كردستان والعراق من خلال ابتكارات التكنولوجيا المالية." },
  compliance: { title:"تماماً", highlight:"منضبط وآمن", subtitle:"نعمل وفقاً للوائح البنك المركزي العراقي مع الامتثال الكامل لمعايير AML/KYC والأمان على مستوى المؤسسات.", kycTitle:"الامتثال لـ KYC / AML", kycDesc:"إجراءات تعريف العميل الشاملة ومكافحة غسل الأموال المتوافقة بالكامل مع متطلبات البنك المركزي العراقي والمعايير الدولية.", dataTitle:"تشفير البيانات", dataDesc:"تشفير SSL/TLS على المستوى العسكري والتوكييل وتخزين البيانات الآمن الذي يضمن الحماية الكاملة للمعلومات المالية الحساسة.", monitoringTitle:"مراقبة المعاملات", monitoringDesc:"كشف الأنشطة المشبوهة المدعوم بالذكاء الاصطناعي ومراقبة الاحتيال في الوقت الفعلي وسلاسل تدقيق شاملة للامتثال التنظيمي." },
  roadmap: { title:"نمو", highlight:"رحلتنا", subtitle:"نهج متدرج لبناء أكثر بنية تحتية للدفعات موثوقية في العراق.", phase1:"المرحلة 1 — الأساس", phase1Title:"تأسيس الشركة والترخيص", phase1Items:["تسجيل الشركة في العراق","تقديم طلب ترخيص البنك المركزي العراقي والموافقة","تأسيس الشراكات البنكية","نشر بنية تحتية POS المادية"], phase2:"المرحلة 2 — التوسع الرقمي", phase2Title:"إطلاق المنصة عبر الإنترنت", phase2Items:["تفعيل بوابة الدفع عبر الإنترنت","منصة إدارة التاجر","لوحة تقارير وتحليلات","تطبيق الهاتف للمتاجر"], phase3:"المرحلة 3 — التوسع والنمو", phase3Title:"النمو الإقليمي", phase3Items:["توسيع الخدمات على مستوى البلاد","الشراكات الدولية","تكاملات fintech المتقدمة","قدرات الدفع عبر الحدود"] },
  tech: { title:"التكنولوجيا", highlight:"بنتنا التحتية", subtitle:"مدعومة بأحدث التقنيات." },
  trusted: { title:"منصة موثوقة", centralBank:"متوافق مع البنك المركزي", krg:"معتمدة من KRG", iqBanks:"البنوك العراقية", merchants:"الشركات" },
  cta: { title:"هل أنت مستعد لتحويل<br/>تجربة <span class='highlight'>الدفع الخاصة بك؟</span>", description:"انضم إلى مئات الشركات العراقية التي تستخدم MoneyShop لقبول المدفوعات الرقمية بشكل آمن وفعال.", primary:"التقدم بطلب لحساب التاجر", secondary:"التواصل مع فريق المبيعات" },
  card: { title:"MoneyShop", highlight:"بطاقة", subtitle:" consolidate إدارة أعمالك المالية في بطاقة واحدة. تعرّف على حلول البطاقات الذكية المصممة خصيصاً للمعاملات المادية عبر POS والدفع عبر الإنترنت والمزيد.", popular:"الأكثر شعبية", standart:{name:"قياسي", price:"مجاني", period:"", features:["تقديم مجاني ورسوم سنوية","5,000 IQD حد المعاملات اليومي","استخدام في مراكز POS والصرافات الآلية","دعم الدفع عبر الإنترنت","إشعارات المعاملات عبر SMS","دعم العملاء الأساسي"], cta:"تقديم الآن"}, silver:{name:"فضي", price:"19,900 IQD", period:"/شهر", features:["50,000 IQD حد المعاملات اليومي","دعم أولوية العملاء","0.7% رسوم المعاملات","إشعارات تطبيق الهاتف","تقارير مصروفات مفصلة","جميع ميزات القياسي"], cta:"تقديم الآن"}, gold:{name:"ذهبي", price:"49,900 IQD", period:"/شهر", features:["250,000 IQD حد المعاملات اليومي","دعم VIP على مدار الساعة","0.3% رسوم المعاملات","خصومات حصرية من الشركاء","معاملات دولية مجانية","تصميم بطاقة مخصص","جميع ميزات الفضي"], cta:"تقديم الآن"} },
  footer: { description:"لوحة إدارة مالية حديثة. تحويلات الأموال وإدارة البطاقات وتتبع الاستثمارات.", services:"الخدمات", servicesList:["أجهزة POS","المدفوعات عبر الإنترنت","روابط الدفع","بوابة التاجر"], company:"الشركة", companyList:["من نحن","الوظائف","الصحافة","المدونة","اتصل بنا"], legal:"قانوني", legalList:["سياسة الخصوصية","شروط الخدمة","سياسة AML","سياسة KYC","سياسة ملفات تعريف الارتباط"], contact:"اتصل بنا", address:"أربيل، إقليم كردستان، العراق", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"الأحد-الخميس: 09:00 - 18:00", copyright:"© 2026 MoneyShop. جميع الحقوق محفوظة.", privacy:"الخصوصية", terms:"الشروط", sitemap:"خريطة الموقع" },
};

const KU: NestedMessages = {
  nav: { services:"Servis", howItWorks:"Şivê Dijî", card:"Karta MoneyShop", features:"Taybetmeh", compliance:"Bihevkirin", roadmap:"Rêna Helebêjê", impact:"Derfet", pricing:"Nirxandin", login:"Têkeve", register:"Qeyd bke", getStarted:"Dest pê bike", logout:"Derkeve", bireysel:"Kesane", kurumsal:"Korporatîv", individual:"Kesane", corporate:"Korporatîv", moneyTransfer:"Veguhestina Pere", investment:"Investment", paymentOperations:"Karên Dreadanê", physicalPayment:"Drewanên Fîzikî bide dest", onlinePayment:"Drewanên Online bide dest", paymentDistribution:"Drewanên veşartî", cardSolutions:"Çözûnên Karta", faq:"Pirsên frec" },
  hero: { titleStart:"Piştêkî", titleHighlight:"Pêşveçûna Dremanê", titleEnd:"ya Dijîtî li Irakê dide", badge:"Platforma Dremanê ya ji Banka Navîn pejirî", description:"MoneyShop li companiesên li Irak û Herêma Kurdistanê altyapiya dremanê ya ewle, bihevkar û bi serkeftî pêşkêş dide, ji POS ê fîzikî heta dervekeftina dremanê ya online.", cta:"Nihaê Bikes", secondary:"Zêdetir Fêr bike", merchants:"Şirkêt", uptime:"Demê Karê", support:"Alîkari" },
  features: { title:"Çima", highlight:"MoneyShop?", subtitle:"Ji bo Irak hatîye avakirin, ji bo pentûka dremanê ya dijîtî hatîye xweşkirin.", phoneScan:"QR Bişopîne", phoneTransfer:"Veguhestin", phoneReports:"Rapor", phoneRecent:"Danûstandinên Dawî", dashboardTitle:"Panelê Gerмонтînî", dashboardDesc:"Hemû danûstandinên xwe, dahatên xwe û mutabakatên xwe bi gerмонтînî li ser panelê tacirê me ya bihevkî bişopîne.", securityTitle:"Ewlekariya Asta Bankayê", securityDesc:"Şîfrekirina her derê danûstandinê, deteksiyona dolandırîkirinê û altyapiya PCI-DSS pejirî.", iqdTitle:"Bêrîkirina IQD Yerel", iqdDesc:"Hemû danûstandin bi Dînarê Irakê tên bêrîkirin û bi otomatîkî di hesaba banka ya we de tên derxistin.", apiTitle:"API ya Bikarhêner FRIENDLY", apiDesc:"API ya REST ya temam bi SDK ji bo entegrasyona hêsantî li ser avahiya xwe ya mijûl û sepanên xwe." },
  services: { title:"Servisên Me", highlight:"Çarçoveyên Temam", subtitle:"Hemû alavên darayî ku hatîye tevîyê ya firmayê te pêdivî heye.", transfersTitle:"Servisa Veguhestinê", fastTitle:"Veguhestina Bilekî", fastDesc:"Pere ji bikarhênên MoneyShop re bi hemberî bişîne.", eftTitle:"EFT", eftDesc:"Pere bi hesabên bankan re bi EFT bişîne.", internationalTitle:"Veguhestina Navneteweyî", internationalDesc:"Pere li her derdoreyê ya cîhanê bişîne.", ibanTitle:"Veguhestina IBAN", ibanDesc:"Pere bi namba IBAN bişîne.", requestTitle:"Pere Davêje", requestDesc:"Ji kesên din pere bivêje.", secureTitle:"Veguhestina Ewle", secureDesc:"Bi ewlekiya pêşveçavî veguhestin bike." },
  how: { title:"Şivê Dijî", highlight:"4 Qadimên Hesantî", subtitle:"Ji qeydkirinê heta dînema te ya yekemîn — me pêşveçûna onboarding bi serkeftî û bilekî dide.", step1Title:"Qeydkirin û KYC", step1Desc:"Belgeyên firmayê xwe bişîne û bi aliyê portalê me ya ewle piştrastkirina nasnameyê temam bike.", step2Title:"Peymana İmza", step2Desc:"Bi nihênînên komîsyonê ya venîhar û mercên bihevkirî peymana tacirê bixwîne û imza bike.", step3Title:"Sakirin û Entegre", step3Desc:"Terminala xwe ya POS bîne an API ya dervekeftina dremanê li sermalê xwe veke.", step4Title:"Dest pê bike", step4Desc:"Bi panela gerмонтînî bi hemberî derhal dardanistinê dest pê bike." },
  impact: { title:"Ekonomîk û", highlight:"Taybetmeha Ewle", subtitle:"Dengewekî bi heviyê li ser ekosistêma darayî ya Irakê avakirin.", digitalTitle:"Bênîn Digital", digitalDesc:"Bênîna paymentên digital li nav beşên firmayan û bikarhênên iraqî bişopîne.", formalTitle:"Ekonomiya Formel", formalDesc:"Bi rêye danûstandinên digital ya venîhar û şopankirî ekonomiya di derve de bi kêmî bike.", fastTitle:"Dardanistina Bilekî", fastDesc:"Firmayan bide dest ku di hemberî û ewle bişîne dardanistinê.", regionalTitle:"Meşîna Herîhatî", regionalDesc:"Li ser developmenta ekonomî ya KRG û Irakê bi rêya fintêkê sêwir bike." },
  compliance: { title:"Temamen", highlight:"Dengdî û Ewle", subtitle:"Bi AML/KYC ya temam bihevkarî û ewlekariya piştevaniyê li navê firmayan li bin dîtina CBI dixwînin.", kycTitle:"Bihevkarîya KYC / AML", kycDesc:"Prosedûrên Nasnamekirina Temam a Mirov û Pêşgirtina Şûyî Pêyî ya bihevkar li ser daxwazên CBI û standardsên navneteweyî.", dataTitle:"Şîfrekirina Daneyan", dataDesc:"Şîfrekirina SSL/TLS a asta serbestiyê, tokenization û depokirina daneyan ewle ya hemû parastina agahiyên darayî ya sensitive dide.", monitoringTitle:"Şopankariya Danûstandinê", monitoringDesc:"Deteksiyona aktivitê ya şûkî bi aliyê zînendekînê, şopankariya dolandırîkirinê bi gerontînî û izên denetimê ya temam ji bo bihevkarîya qanûnî." },
  roadmap: { title:"Meşîn", highlight:"Sefere Me", subtitle:"Ji bo avakirina altyapiya dremanê ya bawertirîn li Irakê çarçoveya qadam bi qadam.", phase1:"QADAMA 1 — BINGEH", phase1Title:"Avakirina Firmayê û Lîsanskirin", phase1Items:["Tomarkirina firmayê li Irakê","Daxwaza lîsansa CBI û pejirandin","Hevkariyên bankan hatîye avakirin","Altyapiya POS a fîzikî hatîye veşardîn"], phase2:"QADAMA 2 — GIHANDERINA DİJÎTAL", phase2Title:"Destpêka Platformê Online", phase2Items:["Destpêka dervekeftina dremanê ya online","Platforma birêveberiya tacirê","Panelê rapor û analyticsê","APP ji bo tacirên"], phase3:"QADAMA 3 — MEŞÎN Û GIHANDERIN", phase3Title:"Meşîna Herîhatî", phase3Items:["Firehkirina servisê li serê welatê","Hevkariyên navneteweyî","Entegrasyonên fintêkên pêşveçavî","Qabiliyên dremanê ser senivirê"] },
  tech: { title:"Teknoloji", highlight:"Altyapiya Me", subtitle:"Bi dîtînên serdemî hatîye hilakirin." },
  trusted: { title:"Platforma Bawerkirî", centralBank:"Bi Banka Navîn re Bihevkirî", krg:"Ji KRG pejirî", iqBanks:"Bankên Irakê", merchants:"Şirkêt" },
  cta: { title:"Amade yî ku<br/>Erêfa <span class='highlight'>Dremanê Xwe Biguherînî?</span>", description:"Bi beşî hezarên firmên iraqîên bibe ku MoneyShop ji bo qabulkirina paymentên digital bi ewle û bi serkeftî bikêrîne.", primary:"Ji bo Hesaba Tacirê Serlê bike", secondary:"Bi Tebeşîra Frîştî Contact bike" },
  card: { title:"MoneyShop", highlight:"Kart", subtitle:"Birêveberiya darayî ya firmayê xwe li ser karta yekê veşartî bike. Bi çarçoveya karta zana ya me ya ji bo POS, paymentên online û zêdetir tanê bêne.", popular:"HERTIKIYÊN", standart:{name:"Standart", price:"Bêxerzî", period:"", features:["Bêxerzî daxwazkirin û salane","5,000 IQD sinûra rojane","Li ser POS û ATM bikêrîne","Desteka paymentên online","Agahdariyên SMS","Desteka piştevaniyê ya bingehîn"], cta:"Nihaê Bikes"}, silver:{name:"Silver", price:"19.900 IQD", period:"/mehe", features:["50.000 IQD sinûra rojane","Desteka piştevaniyê ya pêşîn","0,7% komaşyon","Agahdariyên APPê", "Raporên xerckariyê ya belavkirî","Hemû taybetmehên Standart"], cta:"Nihaê Bikes"}, gold:{name:"Gold", price:"49.900 IQD", period:"/mehe", features:["250.000 IQD sinûra rojane","Desteka VIP 7/24","0,3% komaşyon","Taybetmehên taybet li hevkarên","Veguhestinên navneteweyî bêxerzî","Schema ya karta taybet","Hemû taybetmehên Silver"], cta:"Nihaê Bikes"} },
  footer: { description:"Platforma birêveberiya darayî ya nûjen. Veguhestina pere, serêvebeya karta û şopankariya investmentê.", services:"Servis", servicesList:["Terminalên POS","Paymentên Online","Girêdanên Payment","Portalê Tacirê"], company:"Şirkêt", companyList:["Der barê me","Karîyer","Basên","Blog","Têkiliyê"], legal:"Yasî", legalList:["Siyaseta Nihênîn","Şertên Axmetin","Siyaseta AML","Siyaseta KYC","Siyaseta Çerez"], contact:"Têkiliyê", address:"Erbîl, Herêma Kurdistan, Irak", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"Yek-Şem: 09:00 - 18:00", copyright:"© 2026 MoneyShop. Hemû mafn hatiye parastin.", privacy:"Nihênîn", terms:"Şert", sitemap:"Nexşeya Malperê" },
};

const FR: NestedMessages = {
  nav: { services:"Services", howItWorks:"Comment ça marche", card:"MoneyShop Card", features:"Fonctionnalités", compliance:"Conformité", roadmap:"Feuille de route", impact:"Impact", pricing:"Tarification", login:"Connexion", register:"S'inscrire", getStarted:"Commencer", logout:"Déconnexion", bireysel:"Particulier", kurumsal:"Entreprise", individual:"Particulier", corporate:"Entreprise", moneyTransfer:"Transfert d'argent", investment:"Investissement", paymentOperations:"Opérations de paiement", physicalPayment:"Accepter les paiements physiques", onlinePayment:"Accepter les paiements en ligne", paymentDistribution:"Distribuer les paiements", cardSolutions:"Solutions de cartes", faq:"FAQ" },
  hero: { titleStart:"Alimenter la", titleHighlight:"Révolution du Paiement", titleEnd:"Numérique en Irak", badge:"Fournisseur de services de paiement agréé par la CBI", description:"MoneyShop fournit une infrastructure de paiement sécurisée, conforme et transparente aux entreprises en Irak et au Kurdistan, des terminaux POS physiques aux passerelles de paiement en ligne.", cta:"Postuler maintenant", secondary:"En savoir plus", merchants:"Entreprises", uptime:"Disponibilité", support:"Support" },
  features: { title:"Pourquoi", highlight:"MoneyShop?", subtitle:"Conçu pour l'Irak, pensé pour l'avenir des paiements numériques.", phoneScan:"Scanner QR", phoneTransfer:"Transfert", phoneReports:"Rapports", phoneRecent:"Transactions récentes", dashboardTitle:"Tableau de bord en temps réel", dashboardDesc:"Suivez toutes vos transactions, revenus et rapprochements en temps réel grâce à notre tableau de bord commerçant intuitif.", securityTitle:"Sécurité de niveau bancaire", securityDesc:"Chiffrement de bout en bout protégeant chaque transaction, détection de fraude et infrastructure conforme PCI-DSS.", iqdTitle:"Traitement local en IQD", iqdDesc:"Toutes les transactions sont traitées en dinar irakien avec un règlement automatique vers votre compte bancaire local.", apiTitle:"API conviviale pour développeurs", apiDesc:"API REST complète avec SDK pour une intégration facile avec vos systèmes et applications existants." },
  services: { title:"Nos Services", highlight:"Solutions Complètes", subtitle:"Tous les outils financiers dont votre entreprise a besoin.", transfersTitle:"Services de transfert", fastTitle:"Transfert rapide", fastDesc:"Envoyez de l'argent instantanément aux utilisateurs MoneyShop.", eftTitle:"EFT", eftDesc:"Envoyez de l'argent via EFT.", internationalTitle:"Transfert international", internationalDesc:"Envoyez de l'argent partout dans le monde.", ibanTitle:"Transfert IBAN", ibanDesc:"Envoyez de l'argent avec un IBAN.", requestTitle:"Demander de l'argent", requestDesc:"Demandez de l'argent à d'autres.", secureTitle:"Transfert sécurisé", secureDesc:"Transférez en toute sécurité." },
  how: { title:"Comment ça marche", highlight:"4 Étapes simples", subtitle:"De l'inscription à votre premier paiement — nous rendons le processus d'intégration fluide et rapide.", step1Title:"Inscription & KYC", step1Desc:"Soumettez vos documents professionnels et complétez la vérification d'identité via notre portail sécurisé.", step2Title:"Signer le contrat", step2Desc:"Examinez et signez le contrat commerçant avec des taux de commission et conditions transparents.", step3Title:"Configuration & Intégration", step3Desc:"Obtenez votre terminal PDV ou intégrez notre API passerelle de paiement sur votre site web.", step4Title:"Commencez à accepter", step4Desc:"Commencez à recevoir des paiements instantanément avec un suivi en temps réel." },
  impact: { title:"Impact", highlight:"Économique et Social", subtitle:"Créer un changement positif dans l'écosystème financier irakien.", digitalTitle:"Adoption numérique", digitalDesc:"Accélérer l'adoption des paiements numériques entre les entreprises et les consommateurs irakiens.", formalTitle:"Économie formelle", formalDesc:"Réduire l'économie informelle grâce à des transactions numériques transparentes et traçables.", fastTitle:"Settlement rapide", fastDesc:"Permettre aux entreprises de percevoir des paiements instantanément et en toute sécurité.", regionalTitle:"Croissance régionale", regionalDesc:"Contribuer au développement économique du KRG et de l'Irak grâce à l'innovation fintech." },
  compliance: { title:"Entièrement", highlight:"Réglementé et Sécurisé", subtitle:"Nous opérons conformément aux réglementations de la CBI avec une conformité AML/KYC complète et une sécurité de niveau entreprise.", kycTitle:"Conformité KYC / AML", kycDesc:"Procédures complètes d'identification des clients et de lutte contre le blanchiment d'argent entièrement conformes aux exigences de la CBI et aux normes internationales.", dataTitle:"Chiffrement des Données", dataDesc:"Chiffrement SSL/TLS de niveau militaire, tokenisation et stockage sécurisé des données assurant une protection complète des informations financières sensibles.", monitoringTitle:"Surveillance des Transactions", monitoringDesc:"Détection d'activités suspectes par IA, surveillance anti-fraude en temps réel et pistes d'audit complètes pour la conformité réglementaire." },
  roadmap: { title:"Croissance", highlight:"Notre parcours", subtitle:"Une approche par étapes pour construire l'infrastructure de paiement la plus fiable d'Irak.", phase1:"PHASE 1 — FONDEMENTS", phase1Title:"Création d'entreprise et licence", phase1Items:["Enregistrement de l'entreprise en Irak","Demande et approbation de la licence CBI","Partenariats bancaires établis","Infrastructure POS physique déployée"], phase2:"PHASE 2 — EXPANSION NUMÉRIQUE", phase2Title:"Lancement de la plateforme en ligne", phase2Items:["Activation de la passerelle de paiement en ligne","Plateforme de gestion des commerçants","Tableau de bord de reporting et d'analytiques","Application mobile pour les commerçants"], phase3:"PHASE 3 — MISE À L'ÉCHELLE", phase3Title:"Croissance régionale", phase3Items:["Expansion des services à l'échelle nationale","Partenariats internationaux","Intégrations fintech avancées","Capacités de paiement transfrontalier"] },
  tech: { title:"Technologie", highlight:"Notre Infrastructure", subtitle:"Alimenté par les dernières technologies." },
  trusted: { title:"Plateforme fiable", centralBank:"Conforme à la Banque centrale", krg:"Approuvé par KRG", iqBanks:"Banques irakiennes", merchants:"Entreprises" },
  cta: { title:"Prêt à transformer<br/>votre <span class='highlight'>expérience de paiement?</span>", description:"Rejoignez des centaines d'entreprises irakiennes qui utilisent MoneyShop pour accepter les paiements numériques en toute sécurité et efficacement.", primary:"Postuler pour un compte marchand", secondary:"Contacter l'équipe commerciale" },
  card: { title:"MoneyShop", highlight:"Card", subtitle:"Consolidez la gestion financière de votre entreprise dans une seule carte. Découvrez nos solutions de cartes intelligentes conçues pour les paiements POS, en ligne et plus encore.", popular:"LE PLUS POPULAIRE", standart:{name:"Standard", price:"Gratuit", period:"", features:["Candidature gratuite et cotisation annuelle","Limite de transaction quotidienne de 5 000 IQD","Utilisation aux POS et DAB","Support de paiement en ligne","Notifications SMS des transactions","Support client de base"], cta:"Postuler maintenant"}, silver:{name:"Silver", price:"19 900 IQD", period:"/mois", features:["Limite de transaction quotidienne de 50 000 IQD","Support client prioritaire","Frais de transaction de 0,7%","Notifications de l'application mobile","Rapports de dépenses détaillés","Toutes les fonctionnalités Standard"], cta:"Postuler maintenant"}, gold:{name:"Gold", price:"49 900 IQD", period:"/mois", features:["Limite de transaction quotidienne de 250 000 IQD","Support VIP 24h/24 et 7j/7","Frais de transaction de 0,3%","Remises exclusives partenaires","Transactions internationales gratuites","Design de carte personnalisé","Toutes les fonctionnalités Silver"], cta:"Postuler maintenant"} },
  footer: { description:"Panneau de gestion financier moderne. Transferts, gestion des cartes et suivi des investissements.", services:"Services", servicesList:["Terminaux PAIEMENT","Paiements en ligne","Liens de paiement","Portail marchand"], company:"Entreprise", companyList:["À propos","Carrières","Presse","Blog","Contact"], legal:"Légal", legalList:["Politique de confidentialité","Conditions d'utilisation","Politique AML","Politique KYC","Politique de cookies"], contact:"Contact", address:"Erbil, Région du Kurdistan, Irak", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"Dim-Jeu: 09:00 - 18:00", copyright:"© 2026 MoneyShop. Tous droits réservés.", privacy:"Confidentialité", terms:"Conditions", sitemap:"Plan du site" },
};

const RU: NestedMessages = {
  nav: { services:"Услуги", howItWorks:"Как это работает", card:"MoneyShop Card", features:"Возможности", compliance:"Соответствие", roadmap:"Дорожная карта", impact:"Влияние", pricing:"Цены", login:"Войти", register:"Регистрация", getStarted:"Начать", logout:"Выйти", bireysel:"Физическое лицо", kurumsal:"Корпоративный", individual:"Физическое лицо", corporate:"Корпоративный", moneyTransfer:"Перевод денег", investment:"Инвестиции", paymentOperations:"Платежные операции", physicalPayment:"Приём физических платежей", onlinePayment:"Приём онлайн-платежей", paymentDistribution:"Распределение платежей", cardSolutions:"Карточные решения", faq:"Часто задаваемые вопросы" },
  hero: { titleStart:"Даём мощь", titleHighlight:"цифровой революции", titleEnd:"платежей в Ираке", badge:"Лицензированный поставщик платежных услуг ЦБИ", description:"MoneyShop предоставляет безопасную, соответствующую нормативам и бесперебойную платежную инфраструктуру для бизнеса в Ираке и Курдистане, от физических POS-терминалов до онлайн-платёжных шлюзов.", cta:"Подать заявку", secondary:"Узнать больше", merchants:"Компании", uptime:"Аптайм", support:"Поддержка" },
  features: { title:"Почему", highlight:"MoneyShop?", subtitle:"Создано для Ирака, разработано для будущего цифровых платежей.", phoneScan:"Сканировать QR", phoneTransfer:"Перевод", phoneReports:"Отчёты", phoneRecent:"Последние операции", dashboardTitle:"Панель в реальном времени", dashboardDesc:"Отслеживайте все свои транзакции, доходы и сводки в реальном времени через интуитивную панель продавца.", securityTitle:"Безопасность банковского уровня", securityDesc:"Сквозное шифрование, защищающее каждую транзакцию, обнаружение мошенничества и инфраструктура, соответствующая PCI-DSS.", iqdTitle:"Локальная обработка в IQD", iqdDesc:"Все транзакции обрабатываются в иракском динаре с автоматическим зачислением на ваш локальный банковский счёт.", apiTitle:"API для разработчиков", apiDesc:"Комплексный REST API с SDK для простой интеграции с вашими существующими системами и приложениями." },
  services: { title:"Наши услуги", highlight:"Комплексные решения", subtitle:"Все финансовые инструменты, необходимые вашему бизнесу.", transfersTitle:"Услуги переводов", fastTitle:"Быстрый перевод", fastDesc:"Мгновенная отправка денег пользователям MoneyShop.", eftTitle:"EFT", eftDesc:"Отправка денег на банковские счета через EFT.", internationalTitle:"Международный перевод", internationalDesc:"Отправка денег в любую точку мира.", ibanTitle:"Перевод по IBAN", ibanDesc:"Отправка денег по номеру IBAN.", requestTitle:"Запросить деньги", requestDesc:"Запросите деньги у других.", secureTitle:"Безопасный перевод", secureDesc:"Переводы с расширенной безопасностью." },
  how: { title:"Как это работает", highlight:"4 простых шага", subtitle:"От регистрации до первого платежа — мы делаем процесс онбординга бесшовным и быстрым.", step1Title:"Регистрация и KYC", step1Desc:"Отправьте документы компании и завершите верификацию личности через наш безопасный портал.", step2Title:"Подписание договора", step2Desc:"Изучите и подпишите договор продавца с прозрачными ставками комиссии и условиями.", step3Title:"Настройка и интеграция", step3Desc:"Получите POS-терминал или интегрируйте наш API платёжного шлюза на ваш сайт.", step4Title:"Начните принимать", step4Desc:"Начните принимать платежи мгновенно с отслеживанием в реальном времени." },
  impact: { title:"Экономическое и", highlight:"социальное влияние", subtitle:"Создание позитивных изменений в финансовой экосистеме Ирака.", digitalTitle:"Цифровое внедрение", digitalDesc:"Ускорение внедрения цифровых платежей между иракскими бизнесами и потребителями.", formalTitle:"Формальная экономика", formalDesc:"Сокращение теневой экономики через прозрачные и отслеживаемые цифровые транзакции.", fastTitle:"Быстрое зачисление", fastDesc:"Возможность для бизнеса мгновенно и безопасно получать платежи.", regionalTitle:"Региональный рост", regionalDesc:"Вклад в экономическое развитие КРГ и Ирака через финтех-инновации." },
  compliance: { title:"Полностью", highlight:"Регулируемая и безопасная", subtitle:"Мы работаем в соответствии с нормативами ЦБИ с полным соответствием AML/KYC и безопасностью корпоративного уровня.", kycTitle:"Соответствие KYC / AML", kycDesc:"Комплексные процедуры идентификации клиентов и противодействия отмыванию денег, полностью соответствующие требованиям ЦБИ и международным стандартам.", dataTitle:"Шифрование данных", dataDesc:"Военное шифрование SSL/TLS, токенизация и безопасное хранение данных, обеспечивающие полную защиту конфиденциальной финансовой информации.", monitoringTitle:"Мониторинг транзакций", monitoringDesc:"Обнаружение подозрительной активности на основе ИИ, мониторинг мошенничества в реальном времени и комплексные аудит-трейлы для соответствия нормативам." },
  roadmap: { title:"Рост", highlight:"Наш путь", subtitle:"Поэтапный подход к созданию самой надёжной платёжной инфраструктуры Ирака.", phase1:"ЭТАП 1 — ОСНОВА", phase1Title:"Создание компании и лицензирование", phase1Items:["Регистрация компании в Ираке","Заявка и получение лицензии ЦБИ","Установлены банковские партнёрства","Развёрнута физическая POS-инфраструктура"], phase2:"ЭТАП 2 — ЦИФРОВАЯ ЭКСПАНСИЯ", phase2Title:"Запуск онлайн-платформы", phase2Items:["Активация онлайн-платёжного шлюза","Платформа управления продавцами","Панель отчётов и аналитики","Мобильное приложение для продавцов"], phase3:"ЭТАП 3 — МАСШТАБИРОВАНИЕ", phase3Title:"Региональный рост", phase3Items:["Расширение услуг по всей стране","Международные партнёрства","Продвинутые финтех-интеграции","Кросс-бордовые платёжные возможности"] },
  tech: { title:"Технологии", highlight:"Наша инфраструктура", subtitle:"Работает на новейших технологиях." },
  trusted: { title:"Надёжная платформа", centralBank:"Соответствует Центральному банку", krg:"Одобрено KRG", iqBanks:"Банки Ирака", merchants:"Компании" },
  cta: { title:"Готовы изменить<br/>свой <span class='highlight'>платёжный опыт?</span>", description:"Присоединяйтесь к сотням иракских бизнесов, использующих MoneyShop для безопасного и эффективного приёма цифровых платежей.", primary:"Подать заявку на мерчант-аккаунт", secondary:"Связаться с отделом продаж" },
  card: { title:"MoneyShop", highlight:"Карта", subtitle:"Объедините финансовое управление бизнесом в одной карте. Познакомьтесь с нашими смарт-картами, специально разработанными для POS-терминалов, онлайн-платежей и многого другого.", popular:"САМАЯ ПОПУЛЯРНАЯ", standart:{name:"Стандарт", price:"Бесплатно", period:"", features:["Бесплатная подача заявки и годовой взнос","Лимит транзакций 5 000 IQD в день","Использование в POS и банкоматах","Поддержка онлайн-платежей","SMS-уведомления о транзакциях","Базовая поддержка клиентов"], cta:"Подать заявку"}, silver:{name:"Серебряная", price:"19 900 IQD", period:"/мес", features:["Лимит транзакций 50 000 IQD в день","Приоритетная поддержка клиентов","Комиссия 0,7% за транзакцию","Уведомления в мобильном приложении","Подробные отчёты о расходах","Все функции Стандарт"], cta:"Подать заявку"}, gold:{name:"Золотая", price:"49 900 IQD", period:"/мес", features:["Лимит транзакций 250 000 IQD в день","VIP-поддержка 24/7","Комиссия 0,3% за транзакцию","Эксклюзивные скидки партнёров","Бесплатные международные транзакции","Индивидуальный дизайн карты","Все функции Серебряной"], cta:"Подать заявку"} },
  footer: { description:"Современная панель финансового управления. Переводы, управление картами и отслеживание инвестиций.", services:"Услуги", servicesList:["POS-терминалы","Онлайн-платежи","Платёжные ссылки","Портал продавца"], company:"Компания", companyList:["О нас","Карьера","Пресса","Блог","Контакты"], legal:"Правовая информация", legalList:["Политика конфиденциальности","Условия использования","AML политика","KYC политика","Политика cookie"], contact:"Контакты", address:"Эрбиль, Курдистан, Ирак", phone:"+964 750 123 4567", email:"info@moneyshop.iq", hours:"Вс-Чт: 09:00 - 18:00", copyright:"© 2026 MoneyShop. Все права защищены.", privacy:"Конфиденциальность", terms:"Условия", sitemap:"Карта сайта" },
};

export const messages: Record<Language, NestedMessages> = { tr: TR, en: EN, ar: AR, ku: KU, fr: FR, ru: RU };

// ─── Dashboard flat dict ───────────────────────────────────
const flatDict: FlatDict = {
  "nav.dashboard":{tr:"Genel Bakış",en:"Overview",ar:"نظرة عامة",ku:"Têgihiştinî",fr:"Aperçu",ru:"Обзор"},
  "nav.accounts":{tr:"Hesaplar",en:"Accounts",ar:"الحسابات",ku:"Hesab",fr:"Comptes",ru:"Счета"},
  "nav.transactions":{tr:"İşlem Geçmişi",en:"Transaction History",ar:"سجل المعاملات",ku:"Dîroka Danûstandinan",fr:"Historique",ru:"История"},
  "nav.transfers":{tr:"Para Transferi",en:"Money Transfer",ar:"تحويل الأموال",ku:"Veguhestina Pere",fr:"Transfert",ru:"Перевод"},
  "nav.deposit":{tr:"Para Yatır",en:"Deposit",ar:"إيداع",ku:"Pere Bixe",fr:"Dépôt",ru:"Пополнить"},
  "nav.withdraw":{tr:"Para Çek",en:"Withdraw",ar:"سحب",ku:"Pere Derxe",fr:"Retrait",ru:"Снять"},
  "nav.recurring":{tr:"Tekrarlanan İşlemler",en:"Recurring Transactions",ar:"المعاملات المتكررة",ku:"Danûstandinên Dubare",fr:"Transactions récurrentes",ru:"Повторяющиеся операции"},
  "nav.installments":{tr:"Taksitli Ödemeler",en:"Installment Payments",ar:"المدفوعات بالأقساط",ku:"Dedanên Bi Bêşên",fr:"Paiements échelonnés",ru:"Рассрочка платежей"},
  "nav.support":{tr:"Destek",en:"Support",ar:"الدعم",ku:"Alîkari",fr:"Support",ru:"Поддержка"},
  "nav.portfolio":{tr:"Yatırım Portföyü",en:"Investment Portfolio",ar:"محفظة الاستثمار",ku:"Portfolioya Investimentê",fr:"Portefeuille d'investissement",ru:"Инвестиционный портфель"},
  "nav.reports":{tr:"Raporlar",en:"Reports",ar:"التقارير",ku:"Rapor",fr:"Rapports",ru:"Отчеты"},
  "nav.budgets":{tr:"Bütçeler",en:"Budgets",ar:"الميزانيات",ku:"Budce",fr:"Budgets",ru:"Бюджеты"},
  "nav.categories":{tr:"Kategoriler",en:"Categories",ar:"الفئات",ku:"Kategorî",fr:"Catégories",ru:"Категории"},
  "nav.card":{tr:"MoneyShop Card",en:"MoneyShop Card",ar:"بطاقة MoneyShop",ku:"Karta MoneyShop",fr:"Carte",ru:"Карта"},
  "nav.profile":{tr:"Profil",en:"Profile",ar:"الملف الشخصي",ku:"Profîl",fr:"Profil",ru:"Профиль"},
  "nav.logout":{tr:"Çıkış Yap",en:"Log Out",ar:"تسجيل الخروج",ku:"Derkeve",fr:"Déconnexion",ru:"Выйти"},
  "header.admin":{tr:"Admin",en:"Admin",ar:"الإدارة",ku:"Rêveberî",fr:"Admin",ru:"Админ"},
  "header.dashboard":{tr:"Genel Bakış",en:"Dashboard",ar:"لوحة التحكم",ku:"Panel",fr:"Tableau de bord",ru:"Панель управления"},
  "header.subtitle":{tr:"Finansal durumunuzu takip edin ve yönetin",en:"Track and manage your financial status",ar:"تتبع وأدر حالتك المالية",ku:"Rewşa xwe bişopîne û veşêrîne",fr:"Suivez et gérez votre situation",ru:"Отслеживайте и управляйте финансами"},
  "header.search":{tr:"Ara...",en:"Search...",ar:"بحث...",ku:"Lêbigere...",fr:"Rechercher...",ru:"Поиск..."},
  "header.notifications":{tr:"Bildirimler",en:"Notifications",ar:"الإشعارات",ku:"Agahdarî",fr:"Notifications",ru:"Уведомления"},
  "header.noNotifications":{tr:"Bildirim bulunmuyor",en:"No notifications",ar:"لا توجد إشعارات",ku:"Agahdarî tune ye",fr:"Aucune notification",ru:"Нет уведомлений"},
  "header.accounts":{tr:"Hesaplar",en:"Accounts",ar:"الحسابات",ku:"Hesab",fr:"Comptes",ru:"Счета"},
  "header.transactions":{tr:"İşlem Geçmişi",en:"Transactions",ar:"المعاملات",ku:"Danûstandin",fr:"Transactions",ru:"Операции"},
  "header.categories":{tr:"Kategoriler",en:"Categories",ar:"الفئات",ku:"Kategorî",fr:"Catégories",ru:"Категории"},
  "header.budgets":{tr:"Bütçeler",en:"Budgets",ar:"الميزانيات",ku:"Budce",fr:"Budgets",ru:"Бюджеты"},
  "header.settings":{tr:"Ayarlar",en:"Settings",ar:"الإعدادات",ku:"Eyar",fr:"Paramètres",ru:"Настройки"},
  "header.profile":{tr:"Profil",en:"Profile",ar:"الملف الشخصي",ku:"Profîl",fr:"Profil",ru:"Профиль"},
  "header.recurring":{tr:"Tekrarlanan İşlemler",en:"Recurring Transactions",ar:"المعاملات المتكررة",ku:"Danûstandinên Dubare",fr:"Transactions récurrentes",ru:"Повторяющиеся операции"},
  "header.portfolio":{tr:"Yatırım Portföyü",en:"Investment Portfolio",ar:"محفظة الاستثمار",ku:"Portfolioya Investimentê",fr:"Portefeuille d'investissement",ru:"Инвестиционный портфель"},
  "header.reports":{tr:"Raporlar",en:"Reports",ar:"التقارير",ku:"Rapor",fr:"Rapports",ru:"Отчеты"},
  "header.card":{tr:"MoneyShop Card",en:"MoneyShop Card",ar:"بطاقة MoneyShop",ku:"Karta MoneyShop",fr:"Carte MoneyShop",ru:"Карта MoneyShop"},
  "header.templates":{tr:"Şablonlar",en:"Templates",ar:"القوالب",ku:"Şablon",fr:"Modèles",ru:"Шаблоны"},
  "header.splitBills":{tr:"Ortak Hesap",en:"Split Bills",ar:"حساب مشترك",ku:"Hesabê Beşkirî",fr:"Factures partagées",ru:"Разделение счетов"},
  "header.installments":{tr:"Taksitli Ödemeler",en:"Installments",ar:"بالأقساط",ku:"Bi Bêşên",fr:"Échelonné",ru:"Рассрочка"},
  "header.support":{tr:"Destek",en:"Support",ar:"الدعم",ku:"Alîkari",fr:"Support",ru:"Поддержка"},
  "header.deposit":{tr:"Para Yatır",en:"Deposit",ar:"إيداع",ku:"Pere Bixe",fr:"Dépôt",ru:"Пополнить"},
  "header.withdraw":{tr:"Para Çek",en:"Withdraw",ar:"سحب",ku:"Pere Derxe",fr:"Retrait",ru:"Снять"},
  "dash.welcome":{tr:"Hoş Geldiniz",en:"Welcome",ar:"مرحباً",ku:"Bi xêr hatî",fr:"Bienvenue",ru:"Добро пожаловать"},
  "dash.subtitle":{tr:"Finansal durumunuzu takip edin ve yönetin",en:"Track and manage your financial status",ar:"تتبع وأدر حالتك المالية",ku:"Rewşa xwe bişopîne û veşêrîne",fr:"Suivez et gérez votre situation",ru:"Отслеживайте и управляйте финансами"},
  "dash.newTransaction":{tr:"Yeni İşlem",en:"New Transaction",ar:"معاملة جديدة",ku:"Danûstandina Nû",fr:"Nouvelle transaction",ru:"Новая операция"},
  "dash.totalBalance":{tr:"Toplam Bakiye",en:"Total Balance",ar:"الرصيد الإجمالي",ku:"Bakiya Giştî",fr:"Solde total",ru:"Общий баланс"},
  "dash.totalIncome":{tr:"Toplam Gelir (Bu Ay)",en:"Total Income (This Month)",ar:"إجمالي الدخل (هذا الشهر)",ku:"Dahata Giştî (Ev Mehe)",fr:"Revenu total (ce mois)",ru:"Общий доход (этот месяц)"},
  "dash.totalExpense":{tr:"Toplam Gider (Bu Ay)",en:"Total Expense (This Month)",ar:"إجمالي المصروفات (هذا الشهر)",ku:"Lêçûna Giştî (Ev Mehe)",fr:"Dépense totale (ce mois)",ru:"Общий расход (этот месяц)"},
  "dash.netWorth":{tr:"Net Değer",en:"Net Worth",ar:"صافي القيمة",ku:"Nirxa Net",fr:"Valeur nette",ru:"Чистая стоимость"},
  "dash.recentTransactions":{tr:"Son İşlemler",en:"Recent Transactions",ar:"آخر المعاملات",ku:"Danûstandinên Dawî",fr:"Transactions récentes",ru:"Последние операции"},
  "dash.viewAll":{tr:"Tümü",en:"View All",ar:"عرض الكل",ku:"Hemû bibîne",fr:"Voir tout",ru:"Все"},
  "dash.noData":{tr:"Henüz veri bulunmuyor",en:"No data yet",ar:"لا توجد بيانات بعد",ku:"Hê tu daneyên tune",fr:"Pas encore de données",ru:"Данных пока нет"},
  "dash.completed":{tr:"Tamamlandı",en:"Completed",ar:"مكتمل",ku:"Temam",fr:"Terminé",ru:"Завершено"},
  "dash.pending":{tr:"Beklemede",en:"Pending",ar:"معلق",ku:"Li bendê",fr:"En attente",ru:"В ожидании"},
  "dash.incomeExpense":{tr:"Gelir: {{income}} / Gider: {{expense}}",en:"Income: {{income}} / Expense: {{expense}}",ar:"الدخل: {{income}} / المصروفات: {{expense}}",ku:"Dahat: {{income}} / Lêçûn: {{expense}}",fr:"Revenu: {{income}} / Dépense: {{expense}}",ru:"Доход: {{income}} / Расход: {{expense}}"},
  "dash.income":{tr:"Gelir",en:"Income",ar:"دخل",ku:"Dahat",fr:"Revenu",ru:"Доход"},
  "dash.expense":{tr:"Gider",en:"Expense",ar:"مصروف",ku:"Lêçûn",fr:"Dépense",ru:"Расход"},
  "dash.monthlyChart":{tr:"Aylık Gelir/Gider",en:"Monthly Income/Expense",ar:"الدخل/المصروفات الشهرية",ku:"Dahat/Lêçûna Mehane",fr:"Revenus/Dépenses mensuels",ru:"Ежемесячный доход/расход"},
  "dash.chartSubtitle":{tr:"Son 6 aylık finansal akış",en:"Last 6 months financial flow",ar:"التدفق المالي لآخر 6 أشهر",ku:"Herika darayî ya 6 mehên dawî",fr:"Flux financier des 6 derniers mois",ru:"Финансовый поток за 6 месяцев"},
  "dash.noTransactions":{tr:"Henüz işlem bulunmuyor",en:"No transactions yet",ar:"لا توجد معاملات بعد",ku:"Hê tu danûstandinên tune",fr:"Pas encore de transactions",ru:"Операций пока нет"},
  "dash.noCategory":{tr:"Kategorisiz",en:"Uncategorized",ar:"بدون فئة",ku:"Bêkategorî",fr:"Sans catégorie",ru:"Без категории"},
  "dash.vsLastMonth":{tr:"geçen aya göre",en:"vs last month",ar:"مقارنة بالشهر الماضي",ku:"li gor meha borî",fr:"vs le mois dernier",ru:"по сравнению с прошлым месяцем"},
  "dash.accounts":{tr:"Hesaplarınız",en:"Your Accounts",ar:"حساباتك",ku:"Hesabên Te",fr:"Vos comptes",ru:"Ваши счета"},
  "dash.accountsSubtitle":{tr:"Tüm banka hesaplarınız ve bakiyeleri",en:"All your bank accounts and balances",ar:"جميع حساباتك المصرفية وأرصدتها",ku:"Hemî hesabên te yên bankê û bakiyeyên wan",fr:"Tous vos comptes bancaires",ru:"Все ваши банковские счета"},
  "dash.addAccount":{tr:"Hesap Ekle",en:"Add Account",ar:"إضافة حساب",ku:"Hesabê Zêdeke",fr:"Ajouter un compte",ru:"Добавить счет"},
  "dash.debt":{tr:"Borç",en:"Debt",ar:"دين",ku:"Deyn",fr:"Dette",ru:"Долг"},
  "dash.balance":{tr:"Bakiye",en:"Balance",ar:"الرصيد",ku:"Bakiye",fr:"Solde",ru:"Баланс"},
  "health.title":{tr:"Finansal Sağlık",en:"Financial Health",ar:"الصحة المالية",ku:"Tenduristîya Darayî",fr:"Santé financière",ru:"Финансовое здоровье"},
  "health.subtitle":{tr:"Genel finansal durumunuz",en:"Your overall financial status",ar:"وضعك المالي العام",ku:"Rewşa darayî ya giştî ya we",fr:"Votre situation financière générale",ru:"Ваш общий финансовый статус"},
  "health.savingsRate":{tr:"Tasarruf Oranı",en:"Savings Rate",ar:"معدل التوفير",ku:"Rêja veşartînê",fr:"Taux d'épargne",ru:"Норма сбережений"},
  "health.budgetAdherence":{tr:"Bütçe Uyumu",en:"Budget Adherence",ar:"الامتثال للميزانية",ku:"Bihevkarîya Budceyê",fr:"Respect du budget",ru:"Соблюдение бюджета"},
  "health.emergencyFund":{tr:"Acil Durum Fonu",en:"Emergency Fund",ar:"صندوق الطوارئ",ku:"Fonda Acilen",fr:"Fonds d'urgence",ru:"Резервный фонд"},
  "health.consistency":{tr:"İşlem Tutarlılığı",en:"Transaction Consistency",ar:"اتساق المعاملات",ku:"Bi hevkirîya Danûstandinê",fr:"Cohérence des transactions",ru:"Последовательность операций"},
  "health.months":{tr:"ay",en:"months",ar:"أشهر",ku:"mehe",fr:"mois",ru:"месяцев"},
  "health.days":{tr:"gün",en:"days",ar:"أيام",ku:"roj",fr:"jours",ru:"дней"},
  "health.tips":{tr:"Öneriler",en:"Recommendations",ar:"توصيات",ku:"Pêşniyar",fr:"Recommandations",ru:"Рекомендации"},
  "health.error":{tr:"Hesaplanamadı",en:"Could not calculate",ar:"لم يتم الحساب",ku:"Nehate hesabkirin",fr:"Impossible de calculer",ru:"Не удалось рассчитать"},
  "nav.templates":{tr:"Şablonlar",en:"Templates",ar:"القوالب",ku:"Şablon",fr:"Modèles",ru:"Шаблоны"},
  "nav.splitBills":{tr:"Ortak Hesap",en:"Split Bills",ar:"حساب مشترك",ku:"Hesabê Beşkirî",fr:"Factures partagées",ru:"Разделение счетов"},
  "nav.payments":{tr:"Ödemeler",en:"Payments",ar:"المدفوعات",ku:"Dedan",fr:"Paiements",ru:"Платежи"},
  "nav.admin":{tr:"Yönetici",en:"Admin",ar:"مدير",ku:"Rêveber",fr:"Administrateur",ru:"Администратор"},
  "common.save":{tr:"Kaydet",en:"Save",ar:"حفظ",ku:"Tomar bike",fr:"Enregistrer",ru:"Сохранить"},
  "common.cancel":{tr:"İptal",en:"Cancel",ar:"إلغاء",ku:"Betal bike",fr:"Annuler",ru:"Отмена"},
  "common.delete":{tr:"Sil",en:"Delete",ar:"حذف",ku:"Jê bibe",fr:"Supprimer",ru:"Удалить"},
  "common.edit":{tr:"Düzenle",en:"Edit",ar:"تعديل",ku:"Biguherîne",fr:"Modifier",ru:"Редактировать"},
  "common.add":{tr:"Ekle",en:"Add",ar:"إضافة",ku:"Zêde bike",fr:"Ajouter",ru:"Добавить"},
  "common.search":{tr:"Ara...",en:"Search...",ar:"بحث...",ku:"Lêbigere...",fr:"Rechercher...",ru:"Поиск..."},
  "common.loading":{tr:"Yükleniyor...",en:"Loading...",ar:"جارٍ التحميل...",ku:"Tê barkirin...",fr:"Chargement...",ru:"Загрузка..."},
  "common.refresh":{tr:"Yenile",en:"Refresh",ar:"تحديث",ku:"Nûve bike",fr:"Actualiser",ru:"Обновить"},
  "common.error":{tr:"Hata",en:"Error",ar:"خطأ",ku:"Çewtî",fr:"Erreur",ru:"Ошибка"},
  "common.success":{tr:"Başarılı",en:"Success",ar:"نجاح",ku:"Serkeftî",fr:"Succès",ru:"Успех"},
  "common.back":{tr:"Geri",en:"Back",ar:"رجوع",ku:"Paşve",fr:"Retour",ru:"Назад"},
  "profile.title":{tr:"Profil",en:"Profile",ar:"الملف الشخصي",ku:"Profîl",fr:"Profil",ru:"Профиль"},
  "profile.changePassword":{tr:"Şifre Değiştir",en:"Change Password",ar:"تغيير كلمة المرور",ku:"Şifreyê Biguherîne",fr:"Changer le mot de passe",ru:"Сменить пароль"},
  "budget.title":{tr:"Bütçeler",en:"Budgets",ar:"الميزانيات",ku:"Budce",fr:"Budgets",ru:"Бюджеты"},
  "budget.create":{tr:"Bütçe Oluştur",en:"Create Budget",ar:"إنشاء ميزانية",ku:"Budceyê Çêke",fr:"Créer un budget",ru:"Создать бюджет"},
  "tx.title":{tr:"İşlemler",en:"Transactions",ar:"المعاملات",ku:"Danûstandin",fr:"Transactions",ru:"Операции"},
  "tx.new":{tr:"Yeni İşlem",en:"New Transaction",ar:"معاملة جديدة",ku:"Danûstandina Nû",fr:"Nouvelle transaction",ru:"Новая операция"},
  "transfer.title":{tr:"Para Transferi",en:"Money Transfer",ar:"تحويل الأموال",ku:"Veguhestina Pere",fr:"Transfert",ru:"Перевод"},
  "account.title":{tr:"Hesaplar",en:"Accounts",ar:"الحسابات",ku:"Hesab",fr:"Comptes",ru:"Счета"},
  "account.add":{tr:"Hesap Ekle",en:"Add Account",ar:"إضافة حساب",ku:"Hesabê Zêdeke",fr:"Ajouter",ru:"Добавить"},
  "category.title":{tr:"Kategoriler",en:"Categories",ar:"الفئات",ku:"Kategorî",fr:"Catégories",ru:"Категории"},
  "settings.title":{tr:"Ayarlar",en:"Settings",ar:"الإعدادات",ku:"Eyar",fr:"Paramètres",ru:"Настройки"},
  "admin.title":{tr:"Admin Paneli",en:"Admin Panel",ar:"لوحة الإدارة",ku:"Panela Rêveberiyê",fr:"Panneau admin",ru:"Панель админа"},
  "fraud.title":{tr:"Güvenlik Uyarıları",en:"Security Alerts",ar:"تنبيهات الأمان",ku:"Hişariyên Ewlekariyê",fr:"Alertes de sécurité",ru:"Оповещения безопасности"},
  "fraud.subtitle":{tr:"Oluşan risk uygunlar",en:"Generated risk alerts",ar:"تنبيهات المخاطر المولدة",ku:"Hişariyên mafelê ku hatîye çêkirin",fr:"Alertes de risque générées",ru:"Сгенерированные оповещения о рисках"},
  "fraud.high":{tr:"Yüksek",en:"High",ar:"عالي",ku:"Bilind",fr:"Élevé",ru:"Высокий"},
  "fraud.medium":{tr:"Orta",en:"Medium",ar:"متوسط",ku:"Navîn",fr:"Moyen",ru:"Средний"},
  "fraud.low":{tr:"Düşük",en:"Low",ar:"منخفض",ku:"Kêş",fr:"Faible",ru:"Низкий"},
  "fraud.noAlerts":{tr:"Uyarı bulunmuyor",en:"No alerts",ar:"لا توجد تنبيهات",ku:"Hişariyên tune",fr:"Aucune alerte",ru:"Нет оповещений"},
  "fraud.allClear":{tr:"Her şey normal görünüyor",en:"Everything looks normal",ar:"كل شيء يبدو طبيعيًا",ku:"Her tişt normal dide xwe",fr:"Tout semble normal",ru:"Всё в норме"},
  "cbi.title":{tr:"CBI Kurları",en:"CBI Exchange Rates",ar:"أسعار صرف البنك المركزي",ku:"Kursên CBI",fr:"Taux de change CBI",ru:"Курсы ЦБИ"},
  "cbi.subtitle":{tr:"Irak Merkez Bankası kurları",en:"Central Bank of Iraq rates",ar:"أسعار البنك المركزي العراقي",ku:"Kursên Banka Navîn a Irakê",fr:"Taux de la Banque centrale d'Irak",ru:"Курсы Центрального банка Ирака"},
  "cbi.iqdBasis":{tr:"IQD Baz Kuru",en:"IQD Base Rate",ar:"سعر IQD الأساسي",ku:"Bingehiya Kursa IQD",fr:"Taux de base IQD",ru:"Базовая ставка IQD"},
  "cbi.lastUpdate":{tr:"Son güncelleme",en:"Last updated",ar:"آخر تحديث",ku:"Dawî nûvekirin",fr:"Dernière mise à jour",ru:"Последнее обновление"},
  "cbi.perUSD":{tr:"USD başına",en:"per USD",ar:"لكل دولار",ku:"bi USD re",fr:"par USD",ru:"за USD"},
  "nav.adminPanel":{tr:"Admin Paneli",en:"Admin Panel",ar:"لوحة الإدارة",ku:"Panela Rêveberiyê",fr:"Panneau admin",ru:"Панель админа"},
  "nav.announcements":{tr:"Duyurular",en:"Announcements",ar:"الإعلانات",ku:"Daxwazî",fr:"Annonces",ru:"Объявления"},
  "nav.smsSend":{tr:"SMS Gönder",en:"Send SMS",ar:"إرسال رسالة نصية",ku:" Peyam bişîne",fr:"Envoyer SMS",ru:"Отправить SMS"},
  "nav.notifications":{tr:"Bildirimler",en:"Notifications",ar:"الإشعارات",ku:"Danezan",fr:"Notifications",ru:"Уведомления"},
  "nav.kycDocuments":{tr:"KYC Belgeleri",en:"KYC Documents",ar:"وثائق KYC",ku:"Belgeyên KYC",fr:"Documents KYC",ru:"Документы KYC"},
  "nav.referrals":{tr:"Davet Sistemi",en:"Referrals",ar:" الإحالات",ku:"Davetkirin",fr:"Parrainages",ru:"Рефералы"},
  "nav.devices":{tr:"Cihazlarım",en:"My Devices",ar:"أجهزتي",ku:"Amûrên min",fr:"Mes appareils",ru:"Мои устройства"},
  "nav.contracts":{tr:"Sözleşmeler",en:"Contracts",ar:"العقود",ku:"Şertname",fr:"Contrats",ru:"Договоры"},
  "nav.apiKeys":{tr:"API Anahtarları",en:"API Keys",ar:"مفاتيح API",ku:"Miftehên API",fr:"Clés API",ru:"API ключи"},
  "nav.webhooks":{tr:"Webhook'lar",en:"Webhooks",ar:"ويب هوك",ku:"Webhook",fr:"Webhooks",ru:"Вебхуки"},
  "nav.exchangeHistory":{tr:"Kur Geçmişi",en:"Rate History",ar:"سجل الأسعار",ku:"Dîroka Nexneşî",fr:"Historique des taux",ru:"История курсов"},
  "nav.loginAttempts":{tr:"Giriş Denemeleri",en:"Login Attempts",ar:"محاولات تسجيل الدخول",ku:"Heweldanên çûnê",fr:"Tentatives de connexion",ru:"Попытки входа"},
  "dash.unverifiedAccount":{tr:"Doğrulanmamış Hesap",en:"Unverified Account",ar:"حساب غير موثق",ku:"Hesabê Nexweşkirî",fr:"Compte non vérifié",ru:"Неподтверждённый аккаунт"},
  "dash.verifyPrompt":{tr:"İşlem yapabilmeniz için hesabınızı onaylayınız.",en:"Please verify your account to perform transactions.",ar:"يرجى التحقق من حسابك لإجراء المعاملات.",ku:"Ji bo kirinê danûstandinê hesabê xwe piştrast bikin.",fr:"Veuillez vérifier votre compte pour effectuer des transactions.",ru:"Пожалуйста, подтвердите свой аккаунт для проведения операций."},
  "recurring.title":{tr:"Tekrarlanan İşlemler",en:"Recurring Transactions",ar:"المعاملات المتكررة",ku:"Danûstandinên Dubare",fr:"Transactions récurrentes",ru:"Повторяющиеся операции"},
  "recurring.subtitle":{tr:"Otomatik tekrarlanan işlemleriniz yönetin",en:"Manage your automatic recurring transactions",ar:"إدارة معاملاتك المتكررة التلقائية",ku:"Danûstandinên xwe yên otomatîk bi rêveberî bikin",fr:"Gérez vos transactions récurrentes automatiques",ru:"Управляйте автоматическими повторяющимися операциями"},
  "recurring.active":{tr:"Aktif",en:"Active",ar:"نشط",ku:"Karî",fr:"Actif",ru:"Активные"},
  "recurring.paused":{tr:"Duraklatıldı",en:"Paused",ar:"متوقف مؤقتًا",ku:"Wê dijî",fr:"En pause",ru:"Приостановленные"},
  "recurring.completed":{tr:"Tamamlandı",en:"Completed",ar:"مكتمل",ku:"Temam",fr:"Terminé",ru:"Завершённые"},
  "recurring.cancelled":{tr:"İptal Edildi",en:"Cancelled",ar:"ملغى",ku:"Betal kirin",fr:"Annulé",ru:"Отменённые"},
  "recurring.new":{tr:"Yeni Tekrarlanan İşlem",en:"New Recurring Transaction",ar:"معاملة متكررة جديدة",ku:"Danûstandina Dubare ya Nû",fr:"Nouvelle transaction récurrente",ru:"Новая повторяющаяся операция"},
  "recurring.empty":{tr:"Henüz tekrarlanan işlem bulunmuyor",en:"No recurring transactions yet",ar:"لا توجد معاملات متكررة بعد",ku:"Hê tu danûstandinên dubare tune",fr:"Pas encore de transactions récurrentes",ru:"Повторяющихся операций пока нет"},
  "recurring.emptyDesc":{tr:"Düzenli gelir/giderlerinizi otomatikleştirmek için bir tekrarlanan işlem oluşturun.",en:"Create a recurring transaction to automate your regular income/expenses.",ar:"أنشئ معاملة متكررة لأتمتة دخلك/مصروفاتك النظامية.",ku:"Ji bo otomatîk kirina dahat/lêçûnên xwe ya normal danûstandina dubareyê çêke.",fr:"Créez une transaction récurrente pour automatiser vos revenus/dépenses réguliers.",ru:"Создайте повторяющуюся операцию для автоматизации регулярных доходов/расходов."},
  "installments.title":{tr:"Taksitli Ödemeler",en:"Installment Payments",ar:"المدفوعات بالأقساط",ku:"Dedanên Bi Bêşên",fr:"Paiements échelonnés",ru:"Рассрочка платежей"},
  "installments.subtitle":{tr:"Taksitli alışverişlerinizi takip edin",en:"Track your installment purchases",ar:"تتبع مشترياتك بالأقساط",ku:"Kirinên xwe yên bi bêşên bişopîne",fr:"Suivez vos achats échelonnés",ru:"Отслеживайте покупки в рассрочку"},
  "installments.new":{tr:"Yeni Taksit",en:"New Installment",ar:"قسط جديد",ku:"Bêşa Nû",fr:"Nouvel échelonnement",ru:"Новая рассрочка"},
  "installments.active":{tr:"Aktif Taksit",en:"Active Installment",ar:"القسط النشط",ku:"Bêşa Karî",fr:"Échelonnement actif",ru:"Активная рассрочка"},
  "installments.totalRemaining":{tr:"Kalan Toplam",en:"Total Remaining",ar:"المتبقي الإجمالي",ku:"Giştî ya mayî",fr:"Total restant",ru:"Осталось всего"},
  "installments.monthlyTotal":{tr:"Aylık Toplam",en:"Monthly Total",ar:"المجموع الشهري",ku:"Giştîya Mehan",fr:"Total mensuel",ru:"Итого в месяц"},
  "installments.createTitle":{tr:"Yeni Taksit Oluştur",en:"Create New Installment",ar:"إنشاء قسط جديد",ku:"Bêsha Nû Çêke",fr:"Créer un échelonnement",ru:"Создать рассрочку"},
  "installments.titleLabel":{tr:"Taksit Açıklaması",en:"Installment Description",ar:"وصف القسط",ku:"Şiroveya Bêşê",fr:"Description de l'échelonnement",ru:"Описание рассрочки"},
  "installments.titlePlaceholder":{tr:"ör: iPhone 15 Pro Max",en:"e.g: iPhone 15 Pro Max",ar:"مثال: آيفون 15 برو ماكس",ku:"mîna: iPhone 15 Pro Max",fr:"ex: iPhone 15 Pro Max",ru:"напр: iPhone 15 Pro Max"},
  "installments.totalAmount":{tr:"Toplam Tutar",en:"Total Amount",ar:"المبلغ الإجمالي",ku:"Bereya Giştî",fr:"Montant total",ru:"Общая сумма"},
  "installments.totalPayments":{tr:"Taksit Sayısı",en:"Number of Installments",ar:"عدد الأقساط",ku:"Hejmara Bi Bêşên",fr:"Nombre d'échéances",ru:"Количество платежей"},
  "installments.account":{tr:"Hesap",en:"Account",ar:"الحساب",ku:"Hesab",fr:"Compte",ru:"Счёт"},
  "installments.selectAccount":{tr:"Hesap seçin",en:"Select account",ar:"اختر حساب",ku:"Hesabê hilbijêre",fr:"Sélectionner un compte",ru:"Выберите счёт"},
  "installments.startDate":{tr:"Başlangıç Tarihi",en:"Start Date",ar:"تاريخ البدء",ku:"Dîroka Destpêkê",fr:"Date de début",ru:"Дата начала"},
  "installments.merchantName":{tr:"Üye İşyeri",en:"Merchant",ar:"المتجر",ku:"Dikrî",fr:"Marchand",ru:"Магазин"},
  "installments.merchantPlaceholder":{tr:"Örn: MediaMarkt",en:"e.g: MediaMarkt",ar:"مثال: ميديا ماركت",ku:"mîna: MediaMarkt",fr:"ex: MediaMarkt",ru:"напр: MediaMarkt"},
  "installments.monthlyAmount":{tr:"Aylık Taksit Tutarı",en:"Monthly Installment Amount",ar:"مبلغ القسط الشهري",ku:"Bereya Bêşa Mehan",fr:"Montant mensuel",ru:"Ежемесячный платёж"},
  "installments.create":{tr:"Oluştur",en:"Create",ar:"إنشاء",ku:"Çêke",fr:"Créer",ru:"Создать"},
  "installments.activeInstallments":{tr:"Aktif Taksitler",en:"Active Installments",ar:"الأقساط النشطة",ku:"Bi Bêşên Karî",fr:"Échelonnements actifs",ru:"Активные рассрочки"},
  "installments.noInstallments":{tr:"Henüz taksit bulunmuyor",en:"No installments yet",ar:"لا توجد أقساط بعد",ku:"Hê tu bi bêşên tune",fr:"Pas encore d'échelonnements",ru:"Рассрочек пока нет"},
  "installments.progress":{tr:"İlerleme",en:"Progress",ar:"التقدم",ku:"Pêşkeftin",fr:"Progression",ru:"Прогресс"},
  "installments.monthly":{tr:"Aylık",en:"Monthly",ar:"شهري",ku:"Mehane",fr:"Mensuel",ru:"Ежемесячно"},
  "installments.remaining":{tr:"Kalan",en:"Remaining",ar:"المتبقي",ku:"Mayî",fr:"Restant",ru:"Осталось"},
  "installments.nextPayment":{tr:"Sonraki Ödeme",en:"Next Payment",ar:"الدفعة القادمة",ku:"Dedana Piçûk",fr:"Prochain paiement",ru:"Следующий платёж"},
  "installments.completedInstallments":{tr:"Tamamlanan Taksitler",en:"Completed Installments",ar:"الأقساط المكتملة",ku:"Bi Bêşên Temam",fr:"Échelonnements terminés",ru:"Завершённые рассрочки"},
  "installments.payments":{tr:"taksit",en:"payments",ar:"أقساط",ku:"bêş",fr:"paiements",ru:"платежей"},
  "installments.pay":{tr:"Öde",en:"Pay",ar:"ادفع",ku:"Bibere",fr:"Payer",ru:"Оплатить"},
  "installments.delete":{tr:"Sil",en:"Delete",ar:"حذف",ku:"Jê bibe",fr:"Supprimer",ru:"Удалить"},
  "support.title":{tr:"Destek",en:"Support",ar:"الدعم",ku:"Alîkari",fr:"Support",ru:"Поддержка"},
  "support.subtitle":{tr:"Destek taleplerinizi yönetin",en:"Manage your support tickets",ar:"إدارة تذاكر الدعم",ku:"Daxwazên alîkariyê xwe bi rêveberî bikin",fr:"Gérez vos demandes de support",ru:"Управляйте запросами в поддержку"},
  "support.new":{tr:"Yeni Talep",en:"New Ticket",ar:"تذكرة جديدة",ku:"Daxwaza Nû",fr:"Nouvelle demande",ru:"Новый запрос"},
  "support.createTitle":{tr:"Yeni Destek Talebi Oluştur",en:"Create Support Ticket",ar:"إنشاء تذكرة دعم",ku:"Daxwaza Alîkariyê Çêke",fr:"Créer une demande de support",ru:"Создать запрос в поддержку"},
  "support.subject":{tr:"Konu",en:"Subject",ar:"الموضوع",ku:"Konu",fr:"Sujet",ru:"Тема"},
  "support.subjectPlaceholder":{tr:"Sorununuzu kısaca açıklayın",en:"Briefly describe your issue",ar:"صف مشكلتك باختصار",ku:"Pirsgirêkê xwe bi kurt ve binivîse",fr:"Décrivez brièvement votre problème",ru:"Кратко опишите проблему"},
  "support.description":{tr:"Açıklama",en:"Description",ar:"الوصف",ku:"Şîrove",fr:"Description",ru:"Описание"},
  "support.descriptionPlaceholder":{tr:"Detaylı açıklama yazın",en:"Write a detailed description",ar:"اكتب وصفاً تفصيلياً",ku:"Şîroveya berfireh binivîse",fr:"Écrivez une description détaillée",ru:"Напишите подробное описание"},
  "support.category":{tr:"Kategori",en:"Category",ar:"الفئة",ku:"Kategorî",fr:"Catégorie",ru:"Категория"},
  "support.priority":{tr:"Öncelik",en:"Priority",ar:"الأولوية",ku:"Pêşî",fr:"Priorité",ru:"Приоритет"},
  "support.create":{tr:"Oluştur",en:"Create",ar:"إنشاء",ku:"Çêke",fr:"Créer",ru:"Создать"},
  "support.backToList":{tr:"Listeye Dön",en:"Back to List",ar:"العودة للقائمة",ku:"Li lîsteyê ve",fr:"Retour à la liste",ru:"Назад к списку"},
  "support.staff":{tr:"Destek",en:"Staff",ar:"الدعم",ku:"Alîkari",fr:"Support",ru:"Поддержка"},
  "support.messagePlaceholder":{tr:"Mesajınızı yazın...",en:"Type your message...",ar:"اكتب رسالتك...",ku:"Peyamê xwe binivîse...",fr:"Écrivez votre message...",ru:"Напишите сообщение..."},
  "support.noTickets":{tr:"Henüz destek talebi bulunmuyor",en:"No support tickets yet",ar:"لا توجد تذاكر دعم بعد",ku:"Hê tu daxwazên alîkariyê tune",fr:"Pas encore de demandes de support",ru:"Запросов в поддержку пока нет"},
  "deposit.title":{tr:"Para Yatır",en:"Deposit",ar:"إيداع",ku:"Pere Bixe",fr:"Dépôt",ru:"Пополнить"},
  "deposit.selectMethod":{tr:"Hesabınıza para yatırma yöntemini seçin",en:"Select your deposit method",ar:"اختر طريقة الإيداع",ku:"Rehberiya pere bikirinê xwe hilbijêre",fr:"Choisissez votre méthode de dépôt",ru:"Выберите способ пополнения"},
  "deposit.iban":{tr:"Kendi IBAN'ın ile Yatır",en:"Deposit via IBAN",ar:"إيداع عبر IBAN",ku:"Bi IBAN-ê xwe bixe",fr:"Dépôt via IBAN",ru:"Пополнение через IBAN"},
  "deposit.card":{tr:"Banka/Kredi Kartı ile Yatır",en:"Deposit via Card",ar:"إيداع بالبطاقة",ku:"Bi Karta Bankan bixe",fr:"Dépôt par carte",ru:"Пополнение картой"},
  "deposit.atm":{tr:"ATM'den MoneyShop Card ile Yatır",en:"Deposit via ATM with MoneyShop Card",ar:"إيداع من الصراف الآلي ببطاقة MoneyShop",ku:"Bi MoneyShop Card ve ATM-ê bixe",fr:"Dépôt au DAB avec MoneyShop Card",ru:"Пополнение через банкомат MoneyShop Card"},
  "deposit.recipient":{tr:"Alıcı Adı",en:"Recipient Name",ar:"اسم المستلم",ku:"Navê Qabûlkerê",fr:"Nom du destinataire",ru:"Имя получателя"},
  "deposit.description":{tr:"Açıklama (Zorunlu)",en:"Description (Required)",ar:"الوصف (مطلوب)",ku:"Şîrove (Pêdivî ye)",fr:"Description (Requis)",ru:"Описание (обязательно)"},
  "withdraw.title":{tr:"Para Çek",en:"Withdraw",ar:"سحب",ku:"Pere Derxe",fr:"Retrait",ru:"Снять"},
  "withdraw.selectMethod":{tr:"Hesabınızdan para çekme yöntemini seçin",en:"Select your withdrawal method",ar:"اختر طريقة السحب",ku:"Rehberiya pere çekinê xwe hilbijêre",fr:"Choisissez votre méthode de retrait",ru:"Выберите способ снятия"},
  "withdraw.iban":{tr:"IBAN ile Para Çek",en:"Withdraw via IBAN",ar:"سحب عبر IBAN",ku:"Bi IBAN-ê derxe",fr:"Retrait via IBAN",ru:"Снятие через IBAN"},
  "withdraw.qr":{tr:"QR ile Para Çek",en:"Withdraw via QR",ar:"سحب عبر QR",ku:"Bi QR derxe",fr:"Retrait via QR",ru:"Снятие через QR"},
  "withdraw.card":{tr:"MoneyShop Card ile Para Çek",en:"Withdraw via MoneyShop Card",ar:"سحب ببطاقة MoneyShop",ku:"Bi MoneyShop Card derxe",fr:"Retrait avec MoneyShop Card",ru:"Снятие MoneyShop Card"},
  "card.title":{tr:"MoneyShop Card",en:"MoneyShop Card",ar:"بطاقة MoneyShop",ku:"Karta MoneyShop",fr:"Carte MoneyShop",ru:"Карта MoneyShop"},
  "card.subtitle":{tr:"Kart bilgileriniz ve işlemleriniz",en:"Your card information and transactions",ar:"معلومات بطاقتك وعملياتك",ku:"Agahdariya karta we û karên we",fr:"Vos informations de carte et transactions",ru:"Информация о карте и операции"},
  "card.blockCard":{tr:"Kartı Dondur",en:"Block Card",ar:"تجميد البطاقة",ku:"Kartê Bixwe",fr:"Geler la carte",ru:"Заморозить карту"},
  "card.cancelCard":{tr:"Kartı İptal Et",en:"Cancel Card",ar:"إلغاء البطاقة",ku:"Kartê Betal Bike",fr:"Annuler la carte",ru:"Отменить карту"},
  "card.unblockCard":{tr:"Kartı Aç",en:"Unblock Card",ar:"إلغاء التجميد",ku:"Kartê Veke",fr:"Débloquer la carte",ru:"Разморозить карту"},
  "card.cardHolder":{tr:"Kart Sahibi",en:"Card Holder",ar:"حامل البطاقة",ku:"Xwezayê Karta",fr:"Titulaire",ru:"Держатель"},
  "card.expiryDate":{tr:"Son Kullanma",en:"Expiry Date",ar:"تاريخ الانتهاء",ku:"Dîroka Dawî",fr:"Date d'expiration",ru:"Срок действия"},
  "card.cvv":{tr:"CVV",en:"CVV",ar:"CVV",ku:"CVV",fr:"CVV",ru:"CVV"},
  "card.dailyLimit":{tr:"Günlük Limit",en:"Daily Limit",ar:"الحد اليومي",ku:"Sînûra Rojane",fr:"Limite quotidienne",ru:"Дневной лимит"},
  "card.monthlyLimit":{tr:"Aylık Limit",en:"Monthly Limit",ar:"الحد الشهري",ku:"Sînûra Mehan",fr:"Limite mensuelle",ru:"Месячный лимит"},
  "card.remaining":{tr:"Kalan",en:"Remaining",ar:"المتبقي",ku:"Mayî",fr:"Restant",ru:"Остаток"},
  "card.dailySpent":{tr:"Günlük Harcanan",en:"Daily Spent",ar:"المصروف اليومي",ku:"Roja Xerc",fr:"Dépensé aujourd'hui",ru:"Потрачено сегодня"},
  "card.monthlySpent":{tr:"Aylık Harcanan",en:"Monthly Spent",ar:"المصروف الشهري",ku:"Meha Xerc",fr:"Dépensé ce mois",ru:"Потрачено в месяц"},
  "card.status":{tr:"Durum",en:"Status",ar:"الحالة",ku:"Rewş",fr:"Statut",ru:"Статус"},
  "card.active":{tr:"Aktif",en:"Active",ar:"نشط",ku:"Karî",fr:"Actif",ru:"Активна"},
  "card.blocked":{tr:"Dondurulmuş",en:"Blocked",ar:"مجمدة",ku:"Bixwe",fr:"Bloquée",ru:"Заморожена"},
  "card.cancelled":{tr:"İptal Edilmiş",en:"Cancelled",ar:"ملغاة",ku:"Betal kirin",fr:"Annulée",ru:"Отменена"},
  "card.pending":{tr:"Beklemede",en:"Pending",ar:"معلق",ku:"Li bendê",fr:"En attente",ru:"Ожидает"},
  "card.cardType":{tr:"Kart Tipi",en:"Card Type",ar:"نوع البطاقة",ku:"Cureyê Karta",fr:"Type de carte",ru:"Тип карты"},
  "card.balance":{tr:"Kart Bakiyesi",en:"Card Balance",ar:"رصيد البطاقة",ku:"Bakiyeya Karta",fr:"Solde de la carte",ru:"Баланс карты"},
  "card.issueDate":{tr:"Veriliş Tarihi",en:"Issue Date",ar:"تاريخ الإصدار",ku:"Dîroka Didekirinê",fr:"Date d'émission",ru:"Дата выдачи"},
  "card.upgrade":{tr:"Kart Yükselt",en:"Upgrade Card",ar:"ترقية البطاقة",ku:"Kartê Bilezkirin",fr:"Upgrader la carte",ru:"Улучшить карту"},
  "card.upgradeDesc":{tr:"Daha yüksek limitler ve ayrıcalıklar için kart tipinizi yükseltin.",en:"Upgrade your card type for higher limits and privileges.",ar:"ارتقِ بنوع بطاقتك للحصول على حدود ومزايا أعلى.",ku:"Ji bo sînûrên bilindtir û taybetmehan kartê xwe bilez bike.",fr:"Upgradez votre type de carte pour des limites et des privilèges plus élevés.",ru:"Улучшите тип карты для более высоких лимитов и привилегий."},
  "card.silver":{tr:"Silver",en:"Silver",ar:"فضي",ku:"Silver",fr:"Argent",ru:"Серебряная"},
  "card.gold":{tr:"Gold",en:"Gold",ar:"ذهبي",ku:"Gold",fr:"Or",ru:"Золотая"},
  "card.standart":{tr:"Standart",en:"Standard",ar:"قياسي",ku:"Standart",fr:"Standard",ru:"Стандарт"},
  "card.standard":{tr:"Standart",en:"Standard",ar:"قياسي",ku:"Standart",fr:"Standard",ru:"Стандарт"},
  "card.recentTransactions":{tr:"Kart İşlemleri",en:"Card Transactions",ar:"عمليات البطاقة",ku:"Karên Karta",fr:"Transactions de carte",ru:"Операции по карте"},
  "card.noTransactions":{tr:"Henüz kart işlemi bulunmuyor",en:"No card transactions yet",ar:"لا توجد عمليات بطاقة بعد",ku:"Hê tu karên karta tune",fr:"Pas encore de transactions",ru:"Операций пока нет"},
  "admin.dashboard":{tr:"Admin Paneli",en:"Admin Panel",ar:"لوحة الإدارة",ku:"Panela Rêveberiyê",fr:"Panneau admin",ru:"Панель админа"},
  "admin.dashboardSubtitle":{tr:"Sistem genelindeki istatistikler ve yönetim araçları",en:"System-wide statistics and management tools",ar:"إحصائيات النظام وأدوات الإدارة",ku:"Amarên pergalê û amûrên rêveberiyê",fr:"Statistiques système et outils de gestion",ru:"Системная статистика и инструменты управления"},
  "admin.totalUsers":{tr:"Toplam Kullanıcı",en:"Total Users",ar:"إجمالي المستخدمين",ku:"Biyarîya Giştî",fr:"Total utilisateurs",ru:"Всего пользователей"},
  "admin.activeUsers":{tr:"Aktif Kullanıcı",en:"Active Users",ar:"المستخدمون النشطون",ku:"Biyarîyên Karî",fr:"Utilisateurs actifs",ru:"Активные пользователи"},
  "admin.suspendedUsers":{tr:"Askıdaki Kullanıcı",en:"Suspended Users",ar:"المستخدمون المعلقون",ku:"Biyarîyên Veqetî",fr:"Utilisateurs suspendus",ru:"Приостановленные"},
  "admin.totalAccounts":{tr:"Toplam Hesap",en:"Total Accounts",ar:"إجمالي الحسابات",ku:"Hesabên Gištî",fr:"Total comptes",ru:"Всего счетов"},
  "admin.totalTransactions":{tr:"Toplam İşlem",en:"Total Transactions",ar:"إجمالي المعاملات",ku:"Danûstandinên Gištî",fr:"Total transactions",ru:"Всего операций"},
  "admin.monthlyIncome":{tr:"Bu Ay Gelir",en:"This Month Income",ar:"دخل هذا الشهر",ku:"Dahata Ev Mehe",fr:"Revenu du mois",ru:"Доход за месяц"},
  "admin.monthlyExpense":{tr:"Bu Ay Gider",en:"This Month Expense",ar:"مصروف هذا الشهر",ku:"Lêçûna Ev Mehe",fr:"Dépense du mois",ru:"Расход за месяц"},
  "admin.totalVolume":{tr:"Toplam Hacim",en:"Total Volume",ar:"الحجم الإجمالي",ku:"Hola Gištî",fr:"Volume total",ru:"Общий объём"},
  "admin.avgTransaction":{tr:"Ortalama İşlem",en:"Average Transaction",ar:"متوسط المعاملة",ku:"Navîna Danûstandinê",fr:"Transaction moyenne",ru:"Средняя операция"},
  "admin.userGrowth":{tr:"Kullanıcı Büyümesi",en:"User Growth",ar:"نمو المستخدمين",ku:"Meşîna Biyarîyên",fr:"Croissance des utilisateurs",ru:"Рост пользователей"},
  "admin.noChartData":{tr:"Grafik için veri bulunamadı",en:"No chart data available",ar:"لا توجد بيانات للرسم البياني",ku:"Ji bo grafîkê daneyên tune",fr:"Aucune donnée disponible",ru:"Нет данных для графика"},
  "admin.newUsers":{tr:"Yeni Kullanıcı",en:"New Users",ar:"مستخدمون جدد",ku:"Biyarîyên Nû",fr:"Nouveaux utilisateurs",ru:"Новые пользователи"},
  "admin.yeniKullanici":{tr:"yeni kullanıcı",en:"new users",ar:"مستخدمون جدد",ku:"biyarîyên nû",fr:"nouveaux utilisateurs",ru:"новых пользователей"},
  "admin.transactionDist":{tr:"İşlem Dağılımı",en:"Transaction Distribution",ar:"توزيع المعاملات",ku:"Bêrdanê Danûstandinan",fr:"Distribution des transactions",ru:"Распределение операций"},
  "admin.revenueChart":{tr:"Aylık Gelir/Gider Grafiği",en:"Monthly Income/Expense Chart",ar:"رسم بياني للدخل/المصروف الشهري",ku:"Grafîka Dahat/Lêçûna Mehan",fr:"Graphique revenus/dépenses mensuels",ru:"График доходов/расходов"},
  "admin.recentTransactions":{tr:"Son İşlemler",en:"Recent Transactions",ar:"آخر المعاملات",ku:"Danûstandinên Dawî",fr:"Transactions récentes",ru:"Последние операции"},
  "admin.topUsers":{tr:"En Aktif Kullanıcılar",en:"Top Users",ar:"أكثر المستخدمين نشاطاً",ku:"Biyarîyên Mezin",fr:"Meilleurs utilisateurs",ru:"Топ пользователей"},
  "admin.allTransactions":{tr:"Tüm İşlemler",en:"All Transactions",ar:"جميع المعاملات",ku:"Hemû Danûstandin",fr:"Toutes les transactions",ru:"Все операции"},
  "admin.users.title":{tr:"Kullanıcı Yönetimi",en:"User Management",ar:"إدارة المستخدمين",ku:"Rêberiya Biyarîyên",fr:"Gestion des utilisateurs",ru:"Управление пользователями"},
  "admin.users.filtrele":{tr:"Filtrele",en:"Filter",ar:"تصفية",ku:"Pêl bikin",fr:"Filtrer",ru:"Фильтр"},
  "admin.users.kullanicilar":{tr:"Kullanıcılar",en:"Users",ar:"المستخدمون",ku:"Biyarî",fr:"Utilisateurs",ru:"Пользователи"},
  "admin.users.kullaniciAra":{tr:"Kullanıcı adı, e-posta veya telefon ile ara...",en:"Search by name, email or phone...",ar:"بحث بالاسم أو البريد الإلكتروني أو الهاتف...",ku:"Bi nav, e-posta an telefon bigere...",fr:"Rechercher par nom, email ou téléphone...",ru:"Поиск по имени, email или телефону..."},
  "admin.users.tumRoller":{tr:"Tüm Roller",en:"All Roles",ar:"جميع الأدوار",ku:"Hemû Rol",fr:"Tous les rôles",ru:"Все роли"},
  "admin.users.tumDurumlar":{tr:"Tüm Durumlar",en:"All Statuses",ar:"جميع الحالات",ku:"Hemû Rewş",fr:"Tous les statuts",ru:"Все статусы"},
  "admin.users.bulunamadi":{tr:"Kullanıcı bulunamadı.",en:"No users found.",ar:"لم يتم العثور على مستخدمين.",ku:"Biyarî nehat dîtin.",fr:"Aucun utilisateur trouvé.",ru:"Пользователи не найдены."},
  "admin.users.yenile":{tr:"Yenile",en:"Refresh",ar:"تحديث",ku:"Nûve bike",fr:"Actualiser",ru:"Обновить"},
  "admin.users.kullanici":{tr:"Kullanıcı",en:"User",ar:"مستخدم",ku:"Biyarî",fr:"Utilisateur",ru:"Пользователь"},
  "admin.users.iletisim":{tr:"İletişim",en:"Contact",ar:"جهة الاتصال",ku:"Têkiliyê",fr:"Contact",ru:"Контакт"},
  "admin.users.rol":{tr:"Rol",en:"Role",ar:"الدور",ku:"Rol",fr:"Rôle",ru:"Роль"},
  "admin.users.durum":{tr:"Durum",en:"Status",ar:"الحالة",ku:"Rewş",fr:"Statut",ru:"Статус"},
  "admin.users.guvenlik":{tr:"Güvenlik",en:"Security",ar:"الأمان",ku:"Ewlekari",fr:"Sécurité",ru:"Безопасность"},
  "admin.users.istatistik":{tr:"İstatistik",en:"Statistics",ar:"الإحصائيات",ku:"Amar",fr:"Statistiques",ru:"Статистика"},
  "admin.users.kayit":{tr:"Kayıt",en:"Registration",ar:"التسجيل",ku:"Qeyd",fr:"Inscription",ru:"Регистрация"},
  "admin.users.islem":{tr:"İşlem",en:"Action",ar:"إجراء",ku:"Kirîn",fr:"Action",ru:"Действие"},
  "admin.users.aktif":{tr:"Aktif",en:"Active",ar:"نشط",ku:"Karî",fr:"Actif",ru:"Активен"},
  "admin.users.askida":{tr:"Askıda",en:"Suspended",ar:"معلق",ku:"Veqetî",fr:"Suspendu",ru:"Приостановлен"},
  "admin.users.hesap":{tr:"hesap",en:"accounts",ar:"حسابات",ku:"hesab",fr:"comptes",ru:"счетов"},
  "admin.users.islemSayisi":{tr:"işlem",en:"transactions",ar:"معاملات",ku:"danûstandin",fr:"transactions",ru:"операций"},
  "admin.users.moderator":{tr:"Moderatör",en:"Moderator",ar:"مشرف",ku:"Moderatör",fr:"Modérateur",ru:"Модератор"},
  "admin.users.kullaniciLabel":{tr:"Kullanıcı",en:"User",ar:"مستخدم",ku:"Biyarî",fr:"Utilisateur",ru:"Пользователь"},
  "admin.users.pasif":{tr:"Pasif",en:"Inactive",ar:"غير نشط",ku:"Nêkarî",fr:"Inactif",ru:"Неактивен"},
};
